### ISSUE TITLE
DNS Unavailable notification on Android Beta

### ISSUE THREAD

**Issue by iamstonecutter** [tailscale/tailscale#13151]
### What is the issue?

New Android Beta update produces 'DNS Unavailable' notification occasionally.

### Are there any recent changes that introduced the issue?

Updated to version Tailscale Android 1.71.72

### OS

Android

### OS version

Android 14

### Tailscale version

1.71.72

### Bug report

BUG-beda928a68057863f43c81f7e1191a165a773dc28779f34f6f886b62c1a0c80c-20240814234322Z-79ae383b693c8040

**Comment by agottardo** [comment]
Should be addressed in 1.72.0.

**Comment by plaindocs** [comment]
I'm running 1.72.0-taa448d5a-g from the Play Store, and still have this.

**Comment by kingdomgardens** [comment]
Ditto

**Comment by AlgusDark** [comment]
Same is happening to me with 1.78.3
