### ISSUE TITLE
DNS Unavailable : try to reach internal DNS with an expired device

### ISSUE THREAD

**Issue by guyguy333** [tailscale/tailscale#13470]
### What is the issue?

When session expires, Tailscale DNS is maintained, resulting in this error : DNS Unavailable. Code: dns-forward-failing.
Even if device is expired, Tailscale toggle is ON in macOS menuBar. I need to switch it off to get internet access again (dns resolution to be more accurate). I guess Tailscale should switch it OFF after session is expired in order to restore original DNS of laptop.

### Steps to reproduce

Wait for a session to expire during night, wake up and check your laptop can no longer resolve DNS.

### OS

macOS

### OS version

14.6.1

### Tailscale version

1.74.0

### Bug report

BUG-6fed6c118d5573d71036b8057907541c991652c8cdd15977442202b02b3bb4a7-20240916181211Z-2bc5ab5476cb921d

**Comment by agottardo** [comment]
Hi @guyguy333, we landed a change in 1.74 that was supposed to fix this so I'm really interested in finding out what's happening on your device. Can you share a [sysdiagnose](https://support.kandji.io/support/solutions/articles/72000599404-how-to-generate-a-sysdiagnose-in-macos) from your Mac to `andrea@tailscale.com`? If you can also share the date and time the key expired but DNS stopped working, that'd be amazing.

**Comment by agottardo** [comment]
Do you remember if you were using an exit node when the key expired and you lost DNS access?

**Comment by barnstar** [comment]
@guyguy333 By "token expired" do you mean your Tailscale keys expired requiring a full re-auth?

Also, can you send us a bug report ID please?  Debug/Bug Report.   That should let us track down exactly what we set your DNS to when your keys expired.

**Comment by guyguy333** [comment]
> Do you remember if you were using an exit node when the key expired and you lost DNS access?

No, I almost never use exit node feature.

**Comment by agottardo** [comment]
Can you share the output of `scutil -d -v --dns` when Tailscale is properly running and DNS is resolving? And can you share the output of the same command after the key expires? Feel free to email it if anything confidential is in it.

**Comment by guyguy333** [comment]
> @guyguy333 does the issue persist if you disable/uninstall TripMode? I see in your logs that it is intercepting some DNS traffic meant for the Tailscale forwarder.

I did uninstall TripMode (and so including Network Extension) two days ago. I got the issue this morning.

**Comment by guyguy333** [comment]
> Can you share the output of `scutil -d -v --dns` when Tailscale is properly running and DNS is resolving? And can you share the output of the same command after the key expires? Feel free to email it if anything confidential is in it.

Sure, I will do next time. I didn't see your message before this morning issue.

**Comment by abarisain** [comment]
Hello!

A couple of my coworkers and myself are impacted by this, and have been for a couple months. Sometimes it works, but more often than not it breaks all DNS resolution.

It happens on both macOS and Linux. I wrote down the mac command, but how can the linux users help?

**Comment by kelivel** [comment]
We've just merged a fix that will potentially resolve this issue. Can you update to unstable version 1.75.85 and let us know if you're seeing the correct behavior now?

**Comment by Eclion** [comment]
Hello!
FYI, I updated my Tailscale client to 1.76.1 and I unfortunately still have the issue ("no internet available") on Linux.
