### ISSUE TITLE
ssh ports other than 22 show up as TYPE=Other.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#1362]
SSH ports other than 22 show up as TYPE=Other despite.  It should be reflected as type=ssh.

![image](https://user-images.githubusercontent.com/75628398/108372027-5fd51800-71cc-11eb-85bf-f4a1f0c233cb.png)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2t64x)

**Comment by pirate** [comment]
just curious, closed as wontfix or closed as fixed @catzkorn?

**Comment by bradfitz** [comment]
It's fixed in a different repo. It'll be deployed soon.

**Comment by 33b5e5** [comment]
The fix doesn't seem to be working on all platforms. I see Linux hosts with `SSH` on non-standard ports being detected now, but sshd on Macs using the same non-standard port number are still showing up as `Other`.

I can send screenshots and other details via email if that would be helpful.

**Comment by soniaappasamy** [comment]
@33b5e5 - yeah feel free to send those screenshots over to us at support@tailscale.com and we can take a look for you

**Comment by bradfitz** [comment]
@33b5e5 @soniaappasamy, there's not much we can do here with the App Store version of Tailscale. The sandbox doesn't permit us access to look up the process names holding those ports.

All we get is, partially redacted:

```
2021-03-02 22:33:31.738404 -0800 PST: control: HostInfo: {"IPNVersion":"1.4.5-tb89c65304-gf09ac28c2","BackendLogID":"38bde0c0844faf3a27fbd871a6509e716f8cb5c7acba44c798e177ed6e964c1b","OS":"macOS","OSVersion":"11.2.2","Package":"IPNExtension","Hostname":"XX","GoArch":"amd64","Services":[{"Proto":"tcp","Port":Num1},{"Proto":"tcp","Port":Num2}],"NetInfo":{"MappingVariesByDestIP":false,"HairPinning":false,"WorkingIPv6":false,"WorkingUDP":true,"UPnP":false,"PMP":false,"PCP":false,"PreferredDERP":10,"DERPLatency":{"10-v4":0.011464459,"2-v4":0.021733209,"9-v4":0.06386225}}}
```

That doesn't format way, but the main point is this:

```
"Services":[{"Proto":"tcp","Port":Num1},{"Proto":"tcp","Port":Num2}],
```

We don't get a process name.

/cc @tailscale/frontend

**Comment by bradfitz** [comment]
I suppose the admin panel could educate users about this: "Unknown" or "Tailscale lacks permissions to identify" instead of "Other" or something.

**Comment by soniaappasamy** [comment]
Oh right yes I forgot about that on mac. Being more helpful with the admin panel wording is a good idea.

**Comment by pirate** [comment]
FYI @catzkorn it looks like the fix works for some machines, but we're still seeing many of our non-22 SSH ports on otherwise standard Ubuntu 20.04 machines identified as `Other` instead of `SSH`:

**working example:**
![image](https://user-images.githubusercontent.com/511499/118763789-72500380-b846-11eb-93f4-56b1d5838a7d.png)

**not working examples:**
![Screen Shot 2021-05-19 at 2 00 59 a](https://user-images.githubusercontent.com/511499/118763695-4a60a000-b846-11eb-8290-be896685f966.png)

**Comment by catzkorn** [comment]
Thanks for bringing this to my attention @pirate. I've made a fix.
