### ISSUE TITLE
Tailscale Android constantly crashing on Android 14, 15, despite working connection

### ISSUE THREAD

**Issue by caiphus2k22** [tailscale/tailscale#14125]
### What is the issue?

Tailscale crashes constantly, however this is only visible in android by the system messages "Tailscale stopped repeatedly...". These messages however are disappearing almost immediately, so they are hard to track. ... Still very annoying for the user, though!

Some semi major battery additional consumption is registered, possibly due to the constant restarts (the below log is counting >100 crashes per day.

Ongoing connection to server is not visibly impeded, so it seems that the service is restarted immediately after crash. 

adb logcat -b crash below - excerpt
```
#####
11-16 09:34:56.365  5749  5921 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-7
11-16 09:34:56.365  5749  5921 E AndroidRuntime: Process: com.tailscale.ipn, PID: 5749
11-16 09:34:56.365  5749  5921 E AndroidRuntime: A0.d: lateinit property app has not been initialized
11-16 09:34:56.365  5749  5921 E AndroidRuntime:        at Z3.e.v(Unknown Source:364)
11-16 09:34:56.365  5749  5921 E AndroidRuntime:        at n4.a.k(Unknown Source:8)
11-16 09:34:56.365  5749  5921 E AndroidRuntime:        at P5.L.run(Unknown Source:114)
11-16 09:34:56.365  5749  5921 E AndroidRuntime:        at G2.c.run(Unknown Source:712)
11-16 09:34:56.365  5749  5921 E AndroidRuntime:        at W5.j.run(Unknown Source:2)
11-16 09:34:56.365  5749  5921 E AndroidRuntime:        at W5.a.run(Unknown Source:95)
11-16 09:34:56.365  5749  5921 E AndroidRuntime:        Suppressed: U5.g: [x0{Cancelling}@5d4e3c3, Dispatchers.IO]
11-16 09:35:01.588  6218  6241 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
11-16 09:35:01.588  6218  6241 E AndroidRuntime: Process: com.tailscale.ipn, PID: 6218
11-16 09:35:01.588  6218  6241 E AndroidRuntime: A0.d: lateinit property app has not been initialized
11-16 09:35:01.588  6218  6241 E AndroidRuntime:        at Z3.e.v(Unknown Source:364)
11-16 09:35:01.588  6218  6241 E AndroidRuntime:        at n4.a.k(Unknown Source:8)
11-16 09:35:01.588  6218  6241 E AndroidRuntime:        at P5.L.run(Unknown Source:114)
11-16 09:35:01.588  6218  6241 E AndroidRuntime:        at G2.c.run(Unknown Source:712)
11-16 09:35:01.588  6218  6241 E AndroidRuntime:        at W5.j.run(Unknown Source:2)
11-16 09:35:01.588  6218  6241 E AndroidRuntime:        at W5.a.run(Unknown Source:95)
11-16 09:35:01.588  6218  6241 E AndroidRuntime:        Suppressed: U5.g: [x0{Cancelling}@717f91f, Dispatchers.IO]
11-16 09:35:01.588  6218  6252 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-8
11-16 09:35:01.588  6218  6252 E AndroidRuntime: Process: com.tailscale.ipn, PID: 6218
11-16 09:35:01.588  6218  6252 E AndroidRuntime: A0.d: lateinit property app has not been initialized
11-16 09:35:01.588  6218  6252 E AndroidRuntime:        at Z3.e.v(Unknown Source:364)
11-16 09:35:01.588  6218  6252 E AndroidRuntime:        at n4.a.k(Unknown Source:8)
11-16 09:35:01.588  6218  6252 E AndroidRuntime:        at P5.L.run(Unknown Source:114)
11-16 09:35:01.588  6218  6252 E AndroidRuntime:        at G2.c.run(Unknown Source:712)
11-16 09:35:01.588  6218  6252 E AndroidRuntime:        at W5.j.run(Unknown Source:2)
11-16 09:35:01.588  6218  6252 E AndroidRuntime:        at W5.a.run(Unknown Source:95)
11-16 09:35:01.588  6218  6252 E AndroidRuntime:        Suppressed: U5.g: [x0{Cancelling}@c2bea35, Dispatchers.IO]
11-16 09:35:01.589  6218  6249 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-6
11-16 09:35:01.589  6218  6249 E AndroidRuntime: Process: com.tailscale.ipn, PID: 6218
11-16 09:35:01.589  6218  6249 E AndroidRuntime: A0.d: lateinit property app has not been initialized
11-16 09:35:01.589  6218  6249 E AndroidRuntime:        at Z3.e.v(Unknown Source:364)
11-16 09:35:01.589  6218  6249 E AndroidRuntime:        at n4.a.k(Unknown Source:8)
11-16 09:35:01.589  6218  6249 E AndroidRuntime:        at P5.L.run(Unknown Source:114)
11-16 09:35:01.589  6218  6249 E AndroidRuntime:        at G2.c.run(Unknown Source:712)
11-16 09:35:01.589  6218  6249 E AndroidRuntime:        at W5.j.run(Unknown Source:2)
11-16 09:35:01.589  6218  6249 E AndroidRuntime:        at W5.a.run(Unknown Source:95)
11-16 09:35:01.589  6218  6249 E AndroidRuntime:        Suppressed: U5.g: [x0{Cancelling}@16b46c, Dispatchers.IO]
```
### Steps to reproduce

run tailscale on android 15 QPR 2 Beta 1 on Pixel 9 Pro or android 14 stable on Pixel 7a

### Are there any recent changes that introduced the issue?

Its unlikely that any specific android version is the trigger, the error was present on normal android 15 Beta, QPR 1 Beta, QPR 2 Beta, but also on Android 14 stable on another pixel device.

Tailscale setup per se is pretty standard, and no changes introduced here. Direct connection is established via server-side UPNP, mobile is on home wifi (tailscale disconnected when it crashes) or t-mobile Germany (tailscale connected wo/ exit node when it crashes) when mobile.

### OS

Android

### OS version

Android 14 stable, android 15 beta

### Tailscale version

1.76.6

### Other software

wireguard VPN app present, but off on Pixel 9 pro, no wireguard VPN app on Pixel 7a, so should be not triggering the issue

Bitdefender Android App on both devices, but no feedback from bitdefender that the app would be closed / quarantined or something else...

### Bug report

BUG-9956efd6fdd6eb6a6a5b9792a114f6165c23fb2a8851c400b5d6e925bc61b1bf-20241116130901Z-303701750ea5d4ee

**Comment by agottardo** [comment]
Should be fixed in v1.78.x.

**Comment by caiphus2k22** [comment]
Unfortunately, the issue persists, with a different error trace. New bug report filed.

**Comment by caiphus2k22** [comment]
Hi, just wanted to add that I noticed cases in the tailscale app, where the VPN connection suddently stops, which the notifications showing an active connection (but android is not showing the VPN key symbol anymore. I have reviewed the crash logs for the tailscale app (found ca 820 over the course of one day), but the trace is always the same as in #14314 .

Toggling any quick select action does not bring any immediate reaction like switching the connection back on, the app seems to be perform other tasks first before switching the connection on (waiting time 2-3 seconds).

Updated to Android 15 QPR2 Beta 2 in the meantime, no change.

**Comment by caiphus2k22** [comment]
solved with tailscale 1.79.134
