### ISSUE TITLE
Tailscale operator on Talos v1.8 loadbalancer services does not work

### ISSUE THREAD

**Issue by drzero42** [tailscale/tailscale#14149]
### What is the issue?

I recently migrated from a K3s cluster running Ubuntu 22.04 to a Talos v1.8 cluster.

I have been running Tailscale operator for over a year and have a mix of Ingresses, a connector and a service type LoadBalancer exposed through Tailscale, that all worked on the K3s-cluster. However, on the Talos v1.8 cluster, the connector (subnet router) and LoadBalancer service did not work. Please note that Ingresses (HTTPS) works.

After a bit of research, I found out about the TUN device changes with the new version of runc included in [Talos v1.8](https://www.talos.dev/v1.8/introduction/what-is-new/#accessing-devnettun-in-kubernetes-pods). I have followed the [documentation](https://www.talos.dev/v1.8/kubernetes-guides/configuration/device-plugins/) and deployed the generic-device-plugin and added the needed resource request to a Tailscale proxyclass.

This fixed the connector (subnet router), but not the loadbalancer service.

I don't really see any obvious errors in the log output, but trying to access the exposed port doesn't work.

The logs from the proxy are [here](https://gist.github.com/drzero42/89368bcd03ebc1a2d840de249cf02a31).

### Steps to reproduce

1. Setup a Talos v1.8 cluster
2. Deploy generic-device-plugin for /dev/net/tun access
3. Deploy Tailscale operator with proxyclass that gets access to tun device
4. Deploy [echo-server](https://github.com/jmalloc/echo-server) with a [service type LoadBalancer](https://gist.github.com/drzero42/ac77ba60687f7faf1c00bd8e3888d47a)
5. Try to access the exposed port with curl and observe that nothing happens.

### OS

Linux

### OS version

Talos v1.8.2

### Tailscale version

1.76.6

**Comment by irbekrm** [comment]
Thank you for opening the issue @drzero42 .
This appears to be the same issue as https://github.com/tailscale/tailscale/issues/10814  and https://github.com/tailscale/tailscale/issues/14256.
I believe we have fixed this in latest dev release, see https://github.com/tailscale/tailscale/issues/14256#issuecomment-2514537396
Please let us know if you see any further issues

**Comment by irbekrm** [comment]
This should be fixed in 1.78 (see links https://github.com/tailscale/tailscale/issues/14149#issuecomment-2514545359)

**Comment by abb-corpay** [comment]
I only just got around to really testing this again, and it is still not working. No errors in the logs, but also no replies on traffic to the exposed port. I have tested with `tailscale ping` and that works fine, but traffic to the specified port does not go through. So this might be something else not related to the TUN problem. Any ideas what this could be?

**Comment by bluevulpine** [comment]
@drzero42 I had this problem and I stumbled on a solution which should probably be better documented.

I'm running Talos and cilium; cilium is set up to replace kube-proxy.

There's a note nested under EKS Fargate in the documentation about [Cilium in Kube-Proxy replacement mode.](https://tailscale.com/kb/1236/kubernetes-operator#cilium-in-kube-proxy-replacement-mode)

> This is needed because when Cilium runs in kube-proxy replacement mode with the socket load balancing in Pods' namespaces enabled, connections from Pods to ClusterIPs go over a TCP socket (instead of going out via Pods' veth devices) and thus bypasses Tailscale firewall rules that are attached to [netfilter hooks](https://www.netfilter.org/).

Once I followed the instructions on cilium's site to set socketLB.hostNamespaceOnly=true, I was able to connect to the loadbalancer services not exposed through an ingress.
