### ISSUE TITLE
Resolve Issue Preventing Firefox From Using Tailscale SSH via the Admin Console

### ISSUE THREAD

**Issue by jimmybrancaccio** [tailscale/tailscale#14550]
### What is the issue?

On Windows 11 Pro (24H2) with Mozilla Firefox 133.0.3 (64-bit) I am unable to login to my Tailscale admin console (https://login.tailscale.com/login) and click on the SSH button of a device and have it successfully make an SSH connection. When I do click on the SSH button a new window pops up and says **Connecting to Tailscale...** but nothing else occurs.

![Screenshot 2025-01-06 133839](https://github.com/user-attachments/assets/5713d2ca-16b4-4fa9-be3f-b2425dc4b3c1)

I have attempted to look at the web developer tools in Firefox but nothing useful comes up for me.

A customer has confirmed this works fine in Windows and Google Chrome and I've confirmed it works fine in macOS and Safari.

### Steps to reproduce

1. Obtain a Windows 11 Home/Pro (23H2 or 24H2) device.
2. Setup Tailscale and Tailscale SSH on a device and ensure you have setup ACLs which allow you to access it. Using the default ACL and SSH ACL rules are fine.
3. Log into your admin console - https://login.tailscale.com/login and go to the Machines page at https://login.tailscale.com/admin/machines
4. Click on the SSH button which appears when hover over a device with Tailscale SSH enabled.
5. Observe a new window pops up and says **Connecting to Tailscale...**
6. Observe that even after 30 seconds to 1 minute nothing has changed in the window that popped up.

### OS

Windows

### OS version

Windows 11 Home/Pro (23H2/24H2)

### Tailscale version

1.78.3

**Comment by garrett-ts** [comment]
I can repro this on a Proxmox VM as well - Windows 10.0.19045 - Tailscale version 1.78.1

**Comment by bailey-ts** [comment]
I'm currently experiencing similar behavior on Linux (Fedora 41) in both Firefox and Chrome.

Firefox: hangs indefinitely at `Connecting to Tailscale...` 

Chrome: closes the SSH console window with a `Tailscale SSH encountered an error during the session, the machine may be offline.` toast in the admin console.

Only the Chrome attempt appears to create an SSH Console node on my tailnet, and selecting "SSH to machine..." again, after the console node shows as connected in the admin console and it and the SSH target have a successful handshake ([logs](http://logz0.corp.ts.net:9431/logs?start=2025-01-09T22%3A38%3A00Z&end=2025-01-09T22%3A43%3A00Z&instances=bbc22cb5cc3f90a1cb5e6e3dfec39d724a572fd1d4a04347ce636df36948645f&json=false&service=&match=)), successfully starts an SSH session. Subsequent attempts from Chrome while the console node is still online also succeed, but launching a session from Firefox still hangs.

**Comment by suikan4github** [comment]
I am having the same problem. Firefox shows `Connecting to Tailscale...` and hangs. On the other hand, command-line SSH can connect to Tailscale machines without a problem. 

Failed to connect from  : 
- Windows 11 Pro 10.0.26100 build 26100 (tailscale 1.78.1)
- Firefox 134.0.1(64bit)

Failed to connect  to : 
- Ubuntu Server 24.04 on GCP Comute Engine (tailscale 1.78.1). 
- Ubuntu Server 24.04 on VMWare Workstation Pro (tailscale 1.78.1)

**Comment by cj0nes** [comment]
Having same behavior on Pop_OS 22.04 with Firefox v134.0 connecting to an LMDE 6 machine. Do not know Tailscale version, as cannot connect right now.

**Comment by jpelchat** [comment]
Able to reproduce on 134.0.2 (aarch64) running MacOS 15.2. 
Does not move beyond on "Connecting to Tailscale..."

**Comment by bsi-nvr** [comment]
I'm also able to reproduce this on windows 11 24H2 running firefox 134.0.2. It hangs on connecting to tailscale as mentioned above. Running the command via the terminal works as expected and can ssh into the machine.

**Comment by OpnSrcConstruction** [comment]
I can reproduce this on Windows 10 & 11 & Ubuntu-Studio 24.04.
They should really make a disclaimer in the docs about the web-console ONLY working on chromium based browsers!

**Comment by Senor-bruh** [comment]
Same here with win10 22H2 running Firefox 135.0/Firefox nightly 137.0a1

**Comment by oxtoacart** [comment]
@creachadair reports encountering the same problem with Firefox on MacOS.

**Comment by kliamr** [comment]
> I'm currently experiencing similar behavior on Linux (Fedora 41) in both Firefox and Chrome.
> 
> Firefox: hangs indefinitely at `Connecting to Tailscale...`
> 
> Chrome: closes the SSH console window with a `Tailscale SSH encountered an error during the session, the machine may be offline.` toast in the admin console.
> 
> Only the Chrome attempt appears to create an SSH Console node on my tailnet, and selecting "SSH to machine..." again, after the console node shows as connected in the admin console and it and the SSH target have a successful handshake ([logs](http://logz0.corp.ts.net:9431/logs?start=2025-01-09T22%3A38%3A00Z&end=2025-01-09T22%3A43%3A00Z&instances=bbc22cb5cc3f90a1cb5e6e3dfec39d724a572fd1d4a04347ce636df36948645f&json=false&service=&match=)), successfully starts an SSH session. Subsequent attempts from Chrome while the console node is still online also succeed, but launching a session from Firefox still hangs.

I was having this problem with Chrome on a Debian 12 based distro but it appears to have been resolved with the Tailscale 1.82 update, although not documented in the release notes as far as I could see.

**Comment by gianfelicevincenzo** [comment]
Same problem....

**Comment by oxtoacart** [comment]
I just tried reproducing and could not reproduce on Firefox or Chrome. Is anyone still seeing this?

**Comment by oxtoacart** [comment]
We haven't been able to reproduce, so I'm closing this for now. If this pops up again, please don't hesitate to reopen.

**Comment by slhck** [comment]
I am getting this error on Chrome Version 141.0.7390.55 (Official Build) (arm64) under macOS 15.6.1 with a Tailscale node running 1.88.3 (Linux 6.6.20+rpt-rpi-v8). But it also affects older Tailscale versions on other machines, so it seems to be independent of the actual target.

The window is just stuck at connecting.

Edit: Should probably be disregarded. It was a connection issue that also affected connections directly from my host to the target machines, caused by a different VPN connection running on my host. I was under the assumption that SSH would work independently of my *local* network and instead could be relayed over Tailscale's network when done from the browser.

**Comment by gianfelicevincenzo** [comment]
Almost another year has passed and **the problem is still there!!**

**Comment by rapmarz16** [comment]
im getting this in chrome and firefox

**Comment by heckad** [comment]
+1
