### ISSUE TITLE
forcing port 443 dial due to recent noise dial

### ISSUE THREAD

**Issue by zero1234888** [tailscale/tailscale#14646]
### What is the issue?

just like：https://github.com/tailscale/tailscale/issues/14089

I set up a Headscale server serve on port 80. Following the normal procedure, Tailscale works as expected. 
However, when Headscale experiences an unexpected interruption, Tailscale forcibly attempts to access port 443.

### Steps to reproduce

When the initial connection attempt fails (regardless of the port), the next retry forcibly attempts to access port 443. Since only port 80 is serving the Headscale instance, this retry will fail, triggering a new retry on port 443, which fails again, leading to a perpetual cycle of failures.

```
var forceNoise443 = envknob.RegisterBool("TS_FORCE_NOISE_443")

func (d *Dialer) forceNoise443() bool {
	if forceNoise443() {
		return true
	}

	if d.HealthTracker.LastNoiseDialWasRecent() {
		d.logf("controlhttp: forcing port 443 dial due to recent noise dial")
		return true
	}

	return false
}
```

The configuration option TS_FORCE_NOISE_443 is ineffective in this case. Even if it's set to false, LastNoiseDialWasRecent will still make forceNoise443() to true.

Therefore, a more effective configuration option is needed to determine whether to access port 443. Alternatively, a configuration option should be provided to adjust the time for LastNoiseDialWasRecent (which is currently fixed at 2 minutes).

### OS

Linux

### OS version

Debian 11

### Tailscale version

1.78

**Comment by bradfitz** [comment]
I believe this was fixed recently by 6db220b47834d8c45fd2b9ab34eff860aa5a6d72 for #14563

**Comment by devalgo1** [comment]
I have the same problem. But not on all nodes. It is suspected that this is a problem on the part of the node's router, it does not skip any packets.

**Comment by roddc** [comment]
I am still getting this error, when I am trying to login to 0.0.0.0:8080 Headscale server, but I can login to 127.0.0.1:8080
