### ISSUE TITLE
Funnel not working anymore?

### ISSUE THREAD

**Issue by P-L-T** [tailscale/tailscale#14779]
My tailscale was working just fine for months. I'm using the FoundryVTT application and utilizing tailscale to make my players be able to connect to it - but today it just stopped working. Nobody can connect to my game anymore. When I input the usual "tailscale funnel 30000" command in it just gives me the normal thing and says it's available on the internet just fine, but again, nobody can connect. What gives? My game starts in two days, so I'm pretty desperate for help.

**Comment by irbekrm** [comment]
@P-L-T could you provide us some more info?

- could you generate a bugreport on the funnel node after attempting to connect over funnel?
https://tailscale.com/kb/1227/bug-report?q=bugreport

- are you able to connect to the same endpoint over tailnet (i.e not via funnel)?

- how have you deployed this and node and how is the funnel configured?

**Comment by amorfinv** [comment]
I am also experiencing similar issues with funnel today. Can no longer connect outside of tailnet  (version 1.78.3 with docker sidecar in macos)

BUG-e3ea1bcc142a83c27058f204f33b25c868899a791fc4ab7ef7422f7967816605-20250126092934Z-740714c75cc0768f

**Comment by LucaSarge4** [comment]
Me too, I can no longer connect with funnel since yesterday afternoon.

**Comment by irbekrm** [comment]
cc @bradfitz as we made some changes there recently

I'm just trying to repro now

**Comment by Vexz00** [comment]
Same problem here. I have two Docker containers funneled and they appear with the text "Funnel" in the admin console, but I can no longer access them without an active Tailscale connection. It worked fine until yesterday, from what I can tell.

**Comment by irbekrm** [comment]
Thank you folks,  I can see that there seems to be an is an issue.
When I try to connect to my a funnel node, I get an SSL error
```
$ curl -vv https://ts-servec-22.<my-tailnet>.ts.net:443
* Host ts-servec-22.<my-tailnet>.ts.net:443 was resolved.
* IPv6: 2a00:dd80:3a::131
* IPv4: 176.58.88.82
*   Trying 176.58.88.82:443...
* Connected to ts-servec-22.<my-tailnet>.ts.net (176.58.88.82) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ...
* Closing connection
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to ...
```

We're looking into it

**Comment by irbekrm** [comment]
(Some debugging notes)

It does seem like the issue might be to do with the TLS cert generation on our ingress.
For me, a previously created Funnel node still functions and the fact that I see the newly created node correctly displayed as `Funnel` in the admin panel + the fact that the DNS name gets resolved, but seems like the TLS handshake fails, suggests that somehow we don't allow cert generation for funnel nodes on ingresses anymore

**Comment by lmagyar** [comment]
Win11 v1.78.1 - Total default config

Serve works.

Funnel stopped working yesterday for this node, reinstalled, certs regenerated, nothing helps, the log is full with:

```
2025-01-26T01:57:07.164+01:00: [unexpected] magicsock: derp-4 does not know about peer [xvj9V], removing route
```

serve works, but curl-ing the funnel results in error:
```
* Host xxx.tailxxx.ts.net:xxx was resolved.
* IPv6: xxx
* IPv4: xxx
*   Trying [xxx]:xxx...
* Immediate connect fail for xxx: Network unreachable
*   Trying xxx:xxx...
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* TLS connect error: error:00000000:lib(0)::reason(0)
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to xxx.tailxxx.ts.net:xxx
* closing connection #0
curl: (35) TLS connect error: error:00000000:lib(0)::reason(0)
```

UPDATE: 24h after it first stopped working, still broken, it seems permanent.

**Comment by irbekrm** [comment]
Just a heads up that this is now a known ongoing incident, see our status page https://status.tailscale.com/, but there is a fix in progress.

Thanks to folks here for reporting 🙏🏼

**Comment by P-L-T** [comment]
Is there a prediction as to when the issue should be fixed? Like I said, I have my players waiting for me by Monday and it's important to me that we can make it that day as we have maaaaaajor scheduling issues. :p

**Comment by P-L-T** [comment]
Oops, misclick.

**Comment by bradfitz** [comment]
A fix was deployed. Seems to have worked but we're still verifying.

**Comment by Vexz00** [comment]
Seems to be fixed from what I can tell. It's working again.

**Comment by P-L-T** [comment]
Yeah it works!

**Comment by vhbui02** [comment]
No it's not, it's happening again

**Comment by irbekrm** [comment]
@Silverbullet069 could you please generate a bugreport? (mostly want to know which region your node is in)
 https://tailscale.com/kb/1227/bug-report

**Comment by vhbui02** [comment]
> [@Silverbullet069](https://github.com/Silverbullet069) could you please generate a bugreport? (mostly want to know which region your node is in) https://tailscale.com/kb/1227/bug-report

Okay, here is my bug report:
```
BUG-700a2e961c95e99334d629d5222251639b75e7c3f4a68b8c5ea03dce72603f36-20250601153755Z-c4ee7ba4a562cfb8
```

My node is in Hong Kong region.

**Comment by irbekrm** [comment]
@Silverbullet069 seems like there was an infrastructure issue in that region that now should have been solved, let us know if it's fixed for you and apologies for the issue

**Comment by vhbui02** [comment]
@irbekrm Nope, I still can't curl it from my non-Tailscale device.

**Comment by irbekrm** [comment]
> @irbekrm Nope, I still can't curl it from my non-Tailscale device.

If you get a chance, could you restart that device and let us know if it still doesn't work?
There is a known bug that might have affected your funnel device after the infra was brought back up. We're looking to fix that

**Comment by vhbui02** [comment]
> If you get a chance, could you restart that device

You're right. It does need restarting. Now it's back to work.

P/s: Lucky for Tailscale that I'm about to learn Cloudflare Tunnel today .-.

EDIT: I can curl it, but still can't get access on browser. Hmm that's good enough since I'm exposing directory not a web application.
