### ISSUE TITLE
Taildrive empty after reboot in Windows

### ISSUE THREAD

**Issue by jpelchat** [tailscale/tailscale#14825]
### What is the issue?

When you reboot a Windows machine with a Taildrive folder, the shared folder appears empty to other Tailscale devices until you re-run the `tailscale drive share <name> <path>` command. 

### Steps to reproduce

1. Share a folder over Taildrive on Windows.
2. Add files to it, and confirm you can view those files on other Tailscale devices.
3. Reboot Windows. 
4. Confirm files are no longer visible from other machines. 
5. Re-run `tailscale drive share <name> <path>`.
6. Files now visible again on other machines. 

### Are there any recent changes that introduced the issue?

None

### OS

Windows

### OS version

Windows Server 2025

### Tailscale version

 1.78.1

### Other software

None, brand new install of Windows. 

### Bug report

BUG-17a09d7ab343e76e32901d988c98fb0fbca80d65cdc40dfe6c396c4a068a7f67-20250129190852Z-a3fb2b1dbf5ff5df

**Comment by jpelchat** [comment]
Tested on Linux and issue does not occur.

**Comment by CynderPC** [comment]
Also had this same exact problem. Was able to fix it by re-sharing the file in command prompt. Not too sure what's going on, but I just started using TailDrive 2 days ago, and this isn't giving me a whole lot of confidence...

Rebooted my server last night and my files weren't accessible today.

**Comment by 0XTENDER0** [comment]
it happened to me and the solution i found is making a CMD batch file in the startup of windows that unshare and share again, so every time windows restart it recreate the share and this problem vanished for now, if you are remote from your PC, have a shortcut somewhere available through other means like AnyDesk, and just run the command. it should work.

**Comment by oxtoacart** [comment]
I am able to reproduce. What I observe is:

1. Share folder X
2. List server's shares from client, see folder show up
3. Restart server
4. List server's shares from client, see nothing show up
5. Share folder Y
6. List server's shares from client, see X and Y show up

So, running the share command seems to be initializing something that gets the server to start actually exposing its configured shares. I'll dig into this today.

**Comment by CynderPC** [comment]
So I put my Tailscale into unattended mode, and mine seems to have the file shared at all times. Maybe this is the easiest solution… not sure. I need mine in unattended mode anyway to be able to remote into my computer.

**Comment by oxtoacart** [comment]
This has been fixed in the latest [unstable](https://pkgs.tailscale.com/unstable/) release 1.81.135.

**Comment by 3DBull** [comment]
Still seeing this issue using Version 1.82.5 on Windows 11. After a restart the shared folder appears empty to other machines. I do not have to re-share the drive. Restarting the Tailscale service brings it back. As a work around I have "net stop tailscale" and "net start tailscale" run from scheduler on startup.

**Comment by thomaslrg** [comment]
I don't know if I should open a new ticket, but I'm also experiencing this issue on Ubuntu 24.04 LTS and Tailscale 1.86.2.

### Steps to reproduce

```bash
$ sudo tailscale drive list
```

```text
name    path    as
----    ----    --
```

```bash
$ sudo tailscale drive share xxx /yyy
```

```text
Sharing "/yyy" as "xxx"
```

```bash
$ sudo tailscale drive list
```

```text
name    path            as
----    ------------    ----
xxx    /yyy            root
```

And I confirm I can access the folder on my other devices.

```bash
$ sudo tailscale down
```

```bash
$ sudo tailscale up
```

```bash
$ sudo tailscale drive list
```

```text
name    path    as
----    ----    --
```

And I can't access the folder on my other devices anymore.
