### ISSUE TITLE
iOS 18.5, tailscale App 1.84.0, subnet routing broken

### ISSUE THREAD

**Issue by polarvogel** [tailscale/tailscale#16082]
### What is the issue?

**What is happening:**
iOS devices running Tailscale 1.84.0 can no longer reach devices in advertised subnets via their LAN IPs. The devices can only reach other Tailscale hosts via MagicDNS names or Tailscale IPs, but cannot access any LAN IPs in the advertised subnet(s). This occurs on both WiFi and cellular connections.

**What should happen:**
iOS devices should accept advertised routes and be able to reach all devices in advertised subnets via their LAN IPs, just like all other Tailscale clients and as they did before the update to 1.84.0.

Note: Using an exit node partially works but only provides access to the subnet behind that specific exit node.

### Steps to reproduce

**Initial setup:**
- One or more non-overlapping subnets (e.g., 192.168.1.0/24, 192.168.5.0/24, etc.)
- Subnet router(s) properly advertising routes
- No overlapping with Tailscale's CGNAT range
- Other clients are able to use the advertised routes without Exit Nodes

**Steps to reproduce:**
1. Update iOS client to version 1.84.0
2. Connect iOS device to any network that is not one of the subnets (like cellular)
3. Enable Tailscale VPN without using an exit node
4. Try to ping or connect to any device in the advertised subnet using its LAN IP
5. Observe that the connection fails
6. Use Exit Node, observe that you can ping hosts in the Exit Nodes subnet, but still no other subnet

**Optional clean installation steps (0.1-0.8):**
0.1. Log out of Tailscale client
0.2. Quit Tailscale app completely
0.3. Go to iOS Settings → Tailscale → Enable "Reset Keychain"
0.4. Launch Tailscale app
0.5. Quit Tailscale app
0.6. Delete Tailscale app
0.7. Reboot iPhone/iPad
0.8. Install Tailscale from App Store
0.9. Login to tailnet
Then proceed with steps 2-6 above

### Are there any recent changes that introduced the issue?

The issue appeared immediately after updating to Tailscale iOS 1.84.0. The previous version worked correctly with the same configuration.

### OS

iOS

### OS version

18.5

### Tailscale version

1.84.0

### Other software

- **iOS version**: 18.5
- **Tailscale iOS app**: 1.84.0
- **Coordination server**: Tested with both Tailscale and self-hosted Headscale (same behavior)
- **Subnet routers**: Various (DD-WRT, Linux, Unraid, Apple TV, Docker container etc.)
- **Other working clients**: Linux (various distros), DD-WRT, Apple TV (tvOS 18.5 with Tailscale 1.84.0), Unraid, Dokcer container
- **ACL policy**: Tested with both no ACLs and permissive "allow all" ACL

The issue only affects iOS clients on version 1.84.0. All other clients, including Apple TV on the same Tailscale version, work correctly.

### Bug report

BUG-ceb1c4e4367ed452b67ecca9e27a761a2c9c03c78cda3b98317033a9949feff8-20250525205929Z-c0070de0b576b972

**Comment by mdriesnj** [comment]
I am having a similar issue though slightly different. 

Setup: 
-Linux Docker container (let's call it LinuxA) running tailscale v1.84.0, advertising 192.168.96.0/21 and exit node function.
-Linux Docker container (LinuxB) running tailscale v1.82.5, advertising 192.168.104.0/24 and exit node function. 
-iOS device (18.4.1) running Tailscale v1.84.0 

Steps to recreate:
-If I use no exit node, I CANNOT access any of the above subnets, although I CAN access any of the auto-assigned tailscale network. 
-If I use LinuxA as exit node I can reach any advertised network on 192.168.96.0/21 (as LinuxA can route to any of those networks locally). I CANNOT access 192.168.104.0/24 
-Conversely, if I use LinuxB as exit node, I CAN reach 192.168.104.0/24 but CANNOT reach 192.168.96.0/21. 

I also have the following clients running without issues:
- MacOS v15.4.1 with Tailscale v1.84.0 
- iPadOS v18.4.1 with Tailscale v1.82.0

**Comment by nickoneill** [comment]
Thanks, we're working on a fix for this now.

**Comment by velvetsunshine** [comment]
Still having this issue myself. Not too familiar with github process; will this completed fix be pushed in the next app update? Or should it be fixed already? Thanks

**Comment by barnstar** [comment]
This has been resolved in 1.84.1 which is rolling out now.

New accounts were being created with accept-routes/RouteAll disabled (and iOS had no UI to toggle that setting).

1.84.1 adds the UI to toggle that to true, and new user profiles will have it set to true by default (mirroring the default on all prior versions).   You can correct this on any existing affect install by updating and toggling the new setting for Use Subnet Routes to "on".

**Comment by counterbeing** [comment]
I upgraded to the new 1.84.1 release last night, and it seems I still have the same problem. I do see the new toggle in the UI, but even after toggling it on, i still can't ping any addresses on the LAN that are being advertised by another node. I am however able to do it on a client that's based in Mac OS.

Does anyone have any tips for me?

**Comment by deon-pump** [comment]
I'm also having this same issue on a macos with 1.94.1 tailscale client. I've tried uninstalling and reinstalling several times...
