### ISSUE TITLE
Settings menu missing in iOS app (1.88.1)

### ISSUE THREAD

**Issue by Mr-Technician** [tailscale/tailscale#17124]
The latest version of the iOS app is missing the settings menu in the top right, and it is impossible to set a custom coordination server.

**Comment by iamtechnyx** [comment]
![image](https://github.com/user-attachments/assets/efee78c1-7779-48f1-8e0d-e37ca65a866a)

**Comment by albertsai** [comment]
To add- Settings menu is also missing on iPadOS with v1.88.1

Previous version 1.86.4 is fine

**Comment by elvisimprsntr** [comment]
1. Same issue on iOS 26.0rc1 and iPadOS 26.0rc1.  Can't even get to the screen to submit a bug report. 

2. I have two logins to the same Tailnet, one with admin access, the other with restricted access via ACLs.  I can't toggle between the two accounts like previous versions. Perhaps related to 1.

3. It appears some connect on demand setting are not working.  Example 1: I set do nothing while on cellular, but it still connects.  I can't confirm CoD settings are still setup because of problem 1.    Example 2: I also set do not connect when on my home WiFi.  I happened to notice the iOS Settings->VPN->VPN Status button is greyed out when on local WiFi, which seems to align with my CoD settings. Not sure if this was intentional behavior.  I also have do not connect set for my '25 Bronco Sport CarPlay Wifi, which does not grey out the iOS Settings->VPN->VPN Status button. So at a minimum there seems to be some inconsistency in the button behavior.  I think iOS treats CarPlay WiFi differently than WiFi access points, i.e. it treats CarPlay as a P2P connection and does not actually route data though the connection.  It actually routes data over the cellular modem.  

4. On iPadOS 26.0rc1 even though it shows Tailscale VPN is connected, it never brings up the list of nodes.

**Comment by arduoi** [comment]
Same here with RC build, iPhone 16 Pro Max.

**Comment by Tigo72** [comment]
I'm having this issue with a normal build (18.5), iPhone11. 
The last two testflight releases of the tailscale ios app (1.87.147 and ...154) show the same problem.

**Comment by porrimab** [comment]
I’m experiencing a similar but slightly different bug.

**Environment**
- iPhone 16 (iOS 18.6.2)
- iPad 6th gen (iPadOS 17.7.10)
- Tailscale v1.88.1

**Observed behavior**
- When disconnected from the tailnet, everything works as expected.
- When connected to the tailnet, the device list does not appear, although the tailnet itself works fine.
- If I keep the VPN connected, swipe up to close the Tailscale app, and then relaunch it, the device list temporarily appears.

**Additional information**
- Tried logging out/in and reinstalling the app, but the issue persists.
- This problem did not occur with v1.86.4.

<img width="2048" height="1536" alt="Image" src="https://github.com/user-attachments/assets/dae457d5-0b50-461c-bd8c-28e19ee60112" />

**Comment by ylempereur** [comment]
I have the same problem as @mbzos45 (on both iOS and iPadOS). No UI once connected, until I force-quit and relaunch

**Comment by Fail-Safe** [comment]
> 1. Same issue on iOS 26.0rc1 and iPadOS 26.0rc1

Likewise, though I'm seeing the same issue with the app on both iOS 18.6.2 and iOS 26rc1.

**Comment by juanejot** [comment]
Same issue as @mbzos45 & @ylempereur 
I’m on iOS 18.6.2 on iPhone 13 mini, same change in behavior to not seeing list of tailnet clients, when moving to TailScale 1.86.4 (expected behavior) to 1.88.1 (lack of client list). Also reinstalled to same detrimental behavior.
Relaunch by swiping up DOES bring back the list (after reinstall), but others’ saying it’s temporary has me worried about it staying.

**Comment by luckman212** [comment]
Same - peer list missing even after uninstall / reboot / reinstall. Swipe up force close brings it back, we'll see if it holds. iPhone16Pro, iOS 18.6.2

**Comment by sudocarlos** [comment]
iPhone 16, iOS 18.6.2, Tailscale v1.88.1 (App Store) - also having this problem

**Comment by Janhouse** [comment]
> Same - peer list missing even after uninstall / reboot / reinstall. Swipe up force close brings it back, we'll see if it holds. iPhone16Pro, iOS 18.6.2

Force close brings back the peer list but not the menu, unable to switch between tailnets, configure accounts or on-demand settings. 😬

**Comment by gitkohster** [comment]
Same issue with 1.88.1 on iPadOS and iOS 18.6.2. Had filed Tailscale support request TSS-66414 on Friday

**Comment by reidmex** [comment]
This version can't show the peer list, missing the settings menu.
It is too crappy!

**Comment by seeleclover** [comment]
To add - Settings menu is also missing on iOS with v1.88.1

**Comment by lacouelle** [comment]
On iOS 18.6.2 on iPhone 13 promis with tailscale apps 1.88.1
I have the account menu on the top right of the application, so no issue for me to access to the function.

**Comment by Drallas** [comment]
Settings menu is also missing on my iPhone and iPad Apps both with v1.88.1

**Comment by cz-lucas** [comment]
Same issue here with iOS 18.6.2 (iPhone 16 pro) and IPadOS 16.7.10 (iPad Pro 9.7)

**Comment by Smiley422** [comment]
Same issue here on iOS 18.6.2 (iPhone 13 Pro).

**Comment by nickoneill** [comment]
Hi folks, this will be fixed in 1.88.2 shortly. Thanks for the reports.

**Comment by olivebowl** [comment]
In the meantime while waiting for the App Store release, I've used this as a workaround to just be able to login with a custom coordination server:

1. Install the TestFlight version https://testflight.apple.com/join/tLcYLZJV
2. Login as usual, as the menu is fixed back in that newer version
3. Go to the App Store and install the broken version, but now you are logged in at least :)

**Comment by hehh2001** [comment]
I have the same problem as @mbzos45 (on both iOS17.5   iphone14 pro max). No UI once connected, until I force-quit and relaunch

**Comment by nickoneill** [comment]
This is fixed in 1.88.2 on the app store now. We've phased the rollout so you may not be auto-updated yet but you can always go directly to the listing to update.

**Comment by ylempereur** [comment]
@nickoneill 

> This is fixed in 1.88.2 on the app store now.

Sorry to say, but it's not completely fixed. The menu is present, but the first time you connect, the list does not appear. It still requires a force quit and relaunch to see the list. This can be reproduced easily by disconnecting, force quitting, connecting, no list.

Somethin's still hinky...

**Comment by segfly** [comment]
@nickoneill I agree with @ylempereur - same issue experienced (have to force quit to see other nodes). 

More importantly, I am also seeing odd behavior now with the exit node. There is no way for me to select my exit node now, and unlike before, there is no red banner message complaining that internet access is disabled without an exit node. So I can't get to the internet at all now while on the tailnet, and the only change was this cursed mobile app release.

I appreciate shipping software is not easy, but how did so many issue make it through this release? It would be nice if Tailscale did a bit more testing of their iOS app. 😕

**Comment by nickoneill** [comment]
@segfly you can use the workaround for quitting and restarting the app to get back to devices and exit node picker. This issue is tracking the settings menu issue only.

**Comment by Codelica** [comment]
> This issue is tracking the settings menu issue only.

Is there an official issue to track the missing device list?  I assumed this was covering both and only see a couple related issues without official response.

**Comment by segfly** [comment]
@nickoneill But what I am saying is even after force quitting to see the devices, the exit node picker no longer appears for me. This issue may be for the settings menu, but it's also where I first saw 1.88.2 was announced; I assumed wrongly that 1.88.2 was reverting something that broke all these things.

**Comment by nickoneill** [comment]
@segfly please file a new issue with a screenshot of what you're seeing

**Comment by zooper** [comment]
I can confirm that the profile button with settings is back in 1.88.2 for iOS. Became available for me just now in AppStore.

**Comment by oddlid** [comment]
> Hi folks, this will be fixed in 1.88.2 shortly. Thanks for the reports.

Just installed 1.88.2 on iPadOS 18.6.2 now, and unfortunately, the issue is still there. Still need to force close and re-launch the app to make the device list appear.
