### ISSUE TITLE
Android Tailscale needs to be force stopped to connect after using another VPN

### ISSUE THREAD

**Issue by SegiH** [tailscale/tailscale#17190]
### What is the issue?

I have the Android Tailscale client on my phone and another VPN from a major VPN provider.

When I finish using my VPN, I turn it off.

When I launch the Android Tailscale app and try to slide the toggle, it will not turn on to enable Tailscale.

The only fix is to long press on the app and force stop it. Pressing recents and swiping Tailscale away doesn't work.

I have tested this with multiple VPN apps alongside TS in Android 15 & 16 and have seen this same behavior.

I have also been able to reproduce this on different Android devices, one running Android 15 and the other running Android 16.

### Steps to reproduce

1. Connect to any VPN provider in Android
2. Disconnect the VPN
3. Launch Tailscale and click on the toggle to enable it
4. Tailscale will not connect
5. Force stop Tailscale
6. Launch Tailscale and it will auto connect

### OS

Android

### OS version

Android 16

### Tailscale version

1.86.4

**Comment by zeeshancs07** [comment]
Same issue with android tailscale version:1.88.1.
Android version 15

**Comment by jswinner** [comment]
I can replicate this.  My tasker intents have failed recently and this seems to be the issue, also with 1.88.1.  The notification shows connected, but the main app does not, and refuses to connect.

**Comment by NKDTL** [comment]
Yes, I can confirm this issue. Tested on Android 15 and Android 9. 

Latest not affected version was few months ago but I don't remember which one.

On latest version (1.90.1) this bug still persist.

**Comment by Aleks1015** [comment]
This is still happening on the latest version 1.92.1

**Comment by Aleks1015** [comment]
To be more specific, in my case it is caused by tasker due to lack of VPN on demand on Android.  This only recently started happening in the last few months, I suspected Tailscale being the issue and am now convinced that a recent update has caused this.  

The app is completely unresponsive, forcing the app the close and then opening it allowing tasker to control it seems to work until you clear the notification.

**Comment by SegiH** [comment]
I am not using Tasker but still have this issue in 1.90.9

**Comment by SegiH** [comment]
I have been reviewing the code that is run when you tap on the toggle to enable or disable the VPN in the Android Tailscale app.

When you tap on the toggle, this function is being called:

https://github.com/tailscale/tailscale-android/blob/94f2829e7cfdcf5f8bf9b3529d55f3aee6e7c700/android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt#L201

I see an area in the logic which can prevent the app from enabling the VPN.

On this line

https://github.com/tailscale/tailscale-android/blob/94f2829e7cfdcf5f8bf9b3529d55f3aee6e7c700/android/src/main/java/com/tailscale/ipn/ui/viewModel/MainViewModel.kt#L215

I strongly suspect that on this line `currentState != Ipn.State.Running -> startVPN()`, the state is still "Ipn.State.Running"  even if Tailscale is not the active VPN which prevents startVPN() from getting called. 

I am still looking into this to see if I can figure out how to clear this value at the right time.

**Comment by SegiH** [comment]
I have been working on this issue and I have fixed the code so you can restart the Tailscale VPN without having to force stop the app first.

I would appreciate if someone can test out this fix before I submit a PR to make it public. This version of Tailscale that I am using is a debug version of the app that is installed along side my existing Tailscale Android app.

**Comment by NKDTL** [comment]
@SegiH Good to know, that someone is working on it. I bought new phone and this issue still persist.

**Comment by SegiH** [comment]
I cannot reproduce this issue with my fix which has to do with how VPN states are managed on Android.

Would you mind trying out an APK with this fix to see if it fixes the issue for you too ?

**Comment by NKDTL** [comment]
Ok, I'll try it on another test account. Where can I download modded APK?

**Comment by SegiH** [comment]
I just uploaded it here:

https://limewire.com/d/5jlTZ#GoZfldiP1C

**Comment by NKDTL** [comment]
@SegiH Ok. Tested. First, I connected to another VPN. Then, it is not possible to connect to Tailscale from the notification tile (in your version [as well as in the official one]). But after holding down the tile and entering the app, one tap or sometimes double-tapping 'Connect' actually establishes a connection, unlike the official app. It still doesn't work as it should(from tile), but it works, unlike having to force the official app to stop for months, which doesn't always work anyway. So your modification actually ensures that you can connect without forcing a stop. I connected to another provider and then to Tailscale through your mod a dozen times, and each time, after two presses, the connection stabilized.

It's strange. Other VPNs don't have such problems, they can kill other VPNs and connect without any problems. Only Tailscale has this problem, and this is already the fourth phone with Android I'm testing it on. Both on the official ROMs and on a custom ROMs.

**Comment by SegiH** [comment]
What you are seeing is also consistent with how I tested it.

I didn't use the tile to try and restart TS, I went straight into the app.

Let me look into why the tile isn't restarting TS and see if I can fix that too

**Comment by SegiH** [comment]
When I tested this out, I saw the Tailscale notification when I connected to TS in the app. It was still there when I left the TS app but as soon as I started another VPN app, the Tailscale notification disappeared. I located where the toggle logic happens and made it stop the VPN before starting it similar to how I did it when you're in the app.

Please download the new version of the APK from https://limewire.com/d/FaGBr#QQPYlqJJal

I removed and uploaded a new apk with the same name

**Comment by NKDTL** [comment]
Check link, you send reflink

**Comment by SegiH** [comment]
Thanks I fixed the link

**Comment by NKDTL** [comment]
Now the tile has gone crazy. It shows ‘connected’ even though Tailscale is not connected. When you enter the application, it connects immediately. Then, when you try to disconnect via the tile, it disconnects, but the tile shows Tailscale as connected and you can no longer connect without re-entering the application. After entering the application, it connects immediately.

https://github.com/user-attachments/assets/8fb7e062-520a-4e3a-8f4b-0589e8fc142f

**Comment by SegiH** [comment]
ok thanks for the video. I think I know why the tile logic was wonky so I changed the logic a little bit and tested the quick tile and when TS is enabled via the tile, I go into the app and see that it is enabled. I hope its fixed now.

Hopefully third time is the charm.

https://limewire.com/d/9PxyP#ZA7uuEwzFI

**Comment by NKDTL** [comment]
Now the tile shows ‘connected’ and ‘disconnected’ when clicked, but it still can't launch Tailscale on its own. It can only turn it off when it was previously on. When it shows ‘connected’ and you enter the application, it actually connects immediately. This is a big upgrade. Thanks for your work @SegiH . Is there an official developer here who would consider this issue in future updates to the official application?

**Comment by SegiH** [comment]
Thanks. The quick tile is only meant to toggle Tailscale' state on a single tap and launches the app if you long press on it. That's how it works for me on Android 16.

I will submit my changes to the Tailscale developers through a push request. They have to approve my changes. I'll use this issue as a reference to what I am fixing.

**Comment by qwertyway** [comment]
I can confirm this problem. 

Also I want to add that same problem appears if you simply swipe the app from recents apps (android 16). After that Tailscale app will not connect until force-stopped

**Comment by SegiH** [comment]
This fix should also address that as well. I am pretty sure it's related to the same cause

**Comment by r01k** [comment]
Been seeing this since a few weeks ago. I don't use any other VPN. As others above, I've been using Tasker for years to enable the VPN on demand via app intent. Now the the intent to connect has no effect. Both the `Connect` button and toggle on the UI do nothing either. The problem occurs after the app has been in the background for a few minutes. Have to force stop it and relaunch it for it to work again. Issue persists after clean reinstalling.

**Comment by SegiH** [comment]
This update should fix that issue

**Comment by Bandit** [comment]
I also have this issue. Support ID TSS-77368

**Comment by kari-ts** [comment]
Thanks all for your help bringing this to our attention and @SegiH for submitting a fix. I'd really appreciate it if you could try out our new unstable [here](https://pkgs.tailscale.com/unstable/#android) and please reopen the issue if you are still experiencing it. Thanks!

**Comment by Aleks1015** [comment]
> Thanks all for your help bringing this to our attention and [@SegiH](https://github.com/SegiH) for submitting a fix. I'd really appreciate it if you could try out our new unstable [here](https://pkgs.tailscale.com/unstable/#android) and please reopen the issue if you are still experiencing it. Thanks!

I installed the unstable build and will let you know if I encounter a similar issue

**Comment by robbelt** [comment]
> Thanks all for your help bringing this to our attention and [@SegiH](https://github.com/SegiH) for submitting a fix. I'd really appreciate it if you could try out our new unstable [here](https://pkgs.tailscale.com/unstable/#android) and please reopen the issue if you are still experiencing it. Thanks!

Tried this version. A few times it worked. Today its not working again. Doesnt connect per connect button in tailscale app. But tailscale shows "connected" then in notification bar (Pixel 8 Pro, Android 16), but it is not connected.

**Comment by SegiH** [comment]
The fix for this is PR #742 which is not my PR. My PR is PR #730 which is still open.

I looked at the code behind this and no offense to whoever did PR #742 but I think my approach is better because its a simpler code fix that's been shown to consistently allow you to re-enable Tailscale.

I placed a breakpoint at the location where I later added the new code and consistently saw the VPN status as stopping when trying to reenable it after using another VPN

**Comment by Bandit** [comment]
Yep confirmed that the issue still happens for me with this build, though it's a slight improvement cos now the app doesn't say I'm logged out when I open it while bugged

**Comment by SegiH** [comment]
If I gave you an apk with my fix, would you mind testing it out ?

**Comment by Bandit** [comment]
Can't say I'm thrilled by the idea of installing a Tailscale APK from someone unaffiliated with TS really. Can you reopen this issue?

**Comment by SegiH** [comment]
No I am not able to reopen the issue. I did not close it in the first place. 

I'm not sure if you know how to build from Android Studio but you can install it yourself that way by getting the Tailscale Android code and switching to the branch with my fix.

**Comment by jswinner** [comment]
I installed the unstable, like @robbelt, worked a few times and it became erratic. After using another VPN,  the UI will freeze, needs a fc to restore. Using tasker intents, the notification will show connect, but it is not.  The ui is frozen at log in and the app must be force closed to regain function, resuming the expected connect.  @kari-ts 
Edit thanks
And my workaround for now, I updated my tasker sequences to bludgeon TS close after completing the nightly backups since intents by themselves were insufficient

**Comment by Aleks1015** [comment]
Hi All - Can confirm as well now that the issue is not resolved.  UI becomes unresponsive similar to how it before

**Comment by Bandit** [comment]
In case it helps for testing, it's quite simple to trigger this behaviour:

1) Tell Tasker to "Send intent" with action `com.tailscale.ipn.CONNECT_VPN` on some trigger (e.g. disconnecting from home wifi)
2) Tell Tasker to "Send intent" with action `com.tailscale.ipn.DISCONNECT_VPN` on some trigger (e.g. connecting to home wifi)
3) Toggle your wifi

Why Tailscale can't just build this "at home" functionality into the app, I don't know. It must be a common use case?

**Comment by Aleks1015** [comment]
> In case it helps for testing, it's quite simple to trigger this behaviour:
> 
> 1. Tell Tasker to "Send intent" with action `com.tailscale.ipn.CONNECT_VPN` on some trigger (e.g. disconnecting from home wifi)
> 2. Tell Tasker to "Send intent" with action `com.tailscale.ipn.DISCONNECT_VPN` on some trigger (e.g. connecting to home wifi)
> 3. Toggle your wifi
> 
> Why Tailscale can't just build this "at home" functionality into the app, I don't know. It must be a common use case?

Yes this replicates the issue for me.  As I noted awhile back this started happening during an update at some point mid-2025 or so (time is flying by).  It was flawless until one of the updates

**Comment by SegiH** [comment]
I want to test this in Tasker with the PR that I wrote but it doesn't seem to work for me in Tasker on Android 16.

What version of Android are you guys using ?

**Comment by jswinner** [comment]
> I want to test this in Tasker with the PR that I wrote but it doesn't seem to work for me in Tasker on Android 16.
> 
> What version of Android are you guys using ?

16, S24+ with January update

**Comment by SegiH** [comment]
Can you tell me what settings you used for the tasker task ?

**Comment by jswinner** [comment]
> Can you tell me what settings you used for the tasker task ?

For the intents, this was on, note I had it fire twice to reliably get the connection.  it is a nested task in my backup script
Ts_on
A1: Send Intent [ Action: com.tailscale.ipn.CONNECT_VPN
Cat: None
Package: com.tailscale.ipn  
Class: com.tailscale.ipn.IPNReceiver
Target: Broadcast Receiver ]
If [ %wifiConnected eq yes ]
A2: Wait MS: 0 Seconds:2 Minutes: 0 Hours: 0 Days: 0 ]
A3: Send Intent [ Action: com.tailscale.ipn.CONNECT_VPN
Cat: None
Package: com.tailscale.ipn  
Class: com.tailscale.ipn.IPNReceiver
Target: Broadcast Receiver ]
If [ %wifiConnected eq yes ]  

   Task: Ts_off

    A1: Send Intent [       Action: com.tailscale.ipn.DISCONNECT_VPN
    Cat: None
    Package: com.tailscale.ipn
    Class: com.tailscale.ipn.IPNReceiver
    Target: Broadcast Receiver ]
  

I am using wifi adb now, I am able to kill  TS so that it will restart, at least testing it a few times
Off
A1ADB Wifi Action:
    am force-stop com.tailscale.ipn
    ADB Wifi Action: am kill com.tailscale.ipn
    ADB Wifi Action: svc vpn disable
    Wait: 1 second
    ADB Wifi Action:   svc vpn enable    

The on is now this
	App -> Launch App	Select Tailscale	
	Task -> Wait	Time: 2 second	
	System -> Send Intent	Action: com.tailscale.ipn.CONNECT_VPN
		Package: com.tailscale.ipn	
		Class: com.tailscale.ipn.IPNReceiver	
		Target: Broadcast Receiver	
	App -> Go Home

**Comment by SegiH** [comment]
I created ts_on and switched to TS then switched back to tasker and ran this task. I did this to make sure that TS is running in the background.

I used these settings:

Action: com.tailscale.ipn.CONNECT_VPN
Package: com.tailscale.ipn
Class: com.tailscale.ipn.IPNReceiver
Target: Broadcast Receiver
If:
%wifiConnected eq yes

When I run this task while connected to WiFi, it does not connect TS.

I also tried disconnecting from Wifi and connecting to WiFi and it does not enable TS.

I have another way to test that I mentioned when I opened this issue that doesn't have this issue any more with my fix which stops the vpn service before trying to start it when you toggle the radio button or hit the enable button.

[Link to the code fix for any coders](https://github.com/tailscale/tailscale-android/pull/730/changes/26b133825d57f0509f886f8adf98d9498c3eb533#diff-3a2c80711638bd30ca7fefd927f1b0179e2ecb1c38b4461290d69c319c9c7374R213)

**Comment by jswinner** [comment]
@SegiH You can remove the if from the connect stanza, that is a variable I have.  The intents have always been a bit erratic, but as @Aleks1015 mentioned, it started to be more so in mid 2025.

**Comment by jswinner** [comment]
@SegiH I built with your fix, I note that after a fc of TS, the intents will not restart.  Adding a launch app step to start of the intent fixes that.
.

**Comment by SegiH** [comment]
If you force close TS, it will no longer be running and Task indeed won't be able to launch it correctly. TS has to be running in the background or Tasker will not be able to launch it. That's an Android requirement.

Can you do me a favor and test my build by enabling another VPN and then going back to TS and enabling TS.

That's another good way to test that this big is fixed.

In the official TS available on the play store, once you enable another VPN. You have to force stop TS before you can enable it.

**Comment by jswinner** [comment]
Using the UIs for TS and Mullvad(no tasker), here are some results
TS connected, connect mullvad= TS is disconnected, mullvad is working
Mullvad connected, toggle TS = Mullvad is disconnected, but TS is not connected, connects after another connect.
This is consistent with my experience prior to all of ther trouble with needing to FC TS, and is why there were two intents connect command in my original TS_on.
TS connected toggle mullvad, it disconnects TS and connects Mullvad.  

It appears consitent over a number of toggle sequences.

**Comment by SegiH** [comment]
My test goes like this

Connect TS
Connect Mullvad. TS gets disconnected 
Go back to TS and hit enable once. TS connects and causes Mullvad to disconnect.

Is this what you are experiencing?

**Comment by jswinner** [comment]
No, it takes to 2 TS connect bangs to get it established from mullvad.
  
I have adjusted my ts_on tasker using intents to wake TS first, then 2 connect commands. In my initial testing, that is working reliably to go from mullvad connected to tailscale connected.  Without a fc

**Comment by SegiH** [comment]
When you built the android app, did you grab the source from my repo and switch to the fix/restart-vpn-state-bug branch and build off of that branch ?

I don't have that experience at all. My build connects right away after you tap enable in the TS app after enabling another VPN. I am not using Mullvad but the same principle should apply.

**Comment by jswinner** [comment]
@segih So the 2 tap requirement for me with Mullvad preexisted the needing to do a FC bug.  Just so you have the full picture, I took your segih/fix-730 branch and rebased it locally against the latest source before building.   

I typically have an exit node running.   If i disable that, and fc both apps, it appears to toggle back and forth between them fine as long as I connect and disconnect in the apps. But if I toggle the exit node, then try TS while Mullvad is running, it locks and needs a fc.  Typically, I do not toggle that, so, while still quirky, I can mostly work with.

**Comment by SegiH** [comment]
Ok thanks. That explains the difference since I'm not running TS on Android as an exit node

**Comment by Arche151** [comment]
Thank you for working on this! Really frustrating to not be able to quickly switch between ProtonVPN and Tailscale.

**Comment by biggen1684** [comment]
Guessing this is still an issue.  The only way I can fix this problem on my Galaxy S21 is to reboot it.

**Comment by Bandit** [comment]
Seems like it might be fixed in [1.96.4](https://github.com/tailscale/tailscale-android/releases/tag/1.96.4-t8cf541dfd-g980f12083) which I just manually installed (download APK, turn off "advanced protection" in Settings, install, turn on "advanced protection" again)

**Comment by jswinner** [comment]
I have tested 1.96.4 on my s24 and it appears to have now solved this issue.  Should be added to the next stable release, or use the link @Bandit t provided

**Comment by Arche151** [comment]
I just tested version 1.96.4 and the main problem has been fixed, but an issue remains.

You cannot use Tailscale's Quick Tile to quickly switch between another VPN (ProtonVPN in my case) and Tailscale.

Let me elaborate: When I am connected to Tailscale I can just click on the ProtonVPN quick tile and I'm instantly being connected to ProtonVPN. Then, when I click on the Tailscale quick tile, it doesn't instantly connect me to my Tailnet, but instead opens the Tailscale app and I have to click connect.

I know this is a minor problem, but it would be great, if it could be fixed.

**Comment by jswinner** [comment]
@Arche151 This might be the new expected behavior. The fix applies a more robust teardown of Tailscale when switching VPNs to prevent it from getting stuck in a "stopping" state. While it does require an extra tap in the UI to reconnect, it seems to overcome the previous issue where it wasn't available to connect at all when reverting back.

**Comment by Arche151** [comment]
@jswinner Ah okay I see. So I guess, this a is a seperate issue?

**Comment by jswinner** [comment]
@Arche151 I think this is more of a consequence than a standalone bug, and is the price for better app stability right now.   There are a few other PRs around yet to find there way into a full release yet that may improve re-preparing the vpn to connect.  Also Android 16 imposes additional security that complicates apps starting from the background.

**Comment by Arche151** [comment]
@jswinner Okay, I see. I just thought because Proton lets you quickly connect to a server by just clicking the Quick Tile without having to open the app again, that it shouldn't be that hard to implement for Tailscale.

**Comment by jswinner** [comment]
Those traditional VPNs use a simple point-to-point connection to a single server. Tailscale is a mesh with complex routing to potentially dozens of peer-to-peer connections simultaneously.  
I captured a logcat of the switch, Mullvad to Tailscale and it's ugly. Even with Mullvad disconnected, trying to start Tailscale, Mullvad performed an onRebind, re-asserting itself as the active service.  TS is the more polite app now, and with the updates, will not try to seize the vpn slot while it is already in use. It's only after the second tap that TS is able to assert itself and take over the slot.

**Comment by Arche151** [comment]
@jswinner Ahh okay, thanks for explaining :)

**Comment by therealadrianmmiller** [comment]
its ridiculous to have to reboot the device if you exit/disconnect tailscale...how is this a thing when my other VPN apps have no issue reconnecting after disconnecitng, and theyre written by half assed devs

Pixel 6 Pro, stock A16

**Comment by Bandit** [comment]
I've been running the side-loaded beta release for more than a month with zero issues. Has this not hit the app stores yet?

**Comment by jswinner** [comment]
@therealadrianmmiller   The latest release, 1.98.2 should now address most of the issues, a number of improvements were merged in this and the prior version.

**Comment by Bandit** [comment]
Play Store where I am (New Zealand) is still on `1.96.4`
