### ISSUE TITLE
DNS fails when switching from wifi to mobile data

### ISSUE THREAD

**Issue by Soukyuu** [tailscale/tailscale#17747]
### What is the issue?

It's basically the same issue as #12399

Started happening 3 days ago, "Block connections without vpn" was and is unselected.

Any help is appreciated.

### Steps to reproduce

- Have the latest tailscale and grapheneOS installed.
- Switch between networks
- Attempt to open any webpage.
- Observe the connection timing out (DNS_PROBE_STARTED)
- Wait for the second timeout (DNS_PROBE_FINISHED_BAD_CONFIG)
- switch back to the previous network
- reload the page
- DNS problem is now gone

Disconnect and reconnect to the tailnet fixes the problem.

### Are there any recent changes that introduced the issue?

GrapheneOS system update and the updat2 from tailscale 1.88.4

### OS

Android

### OS version

16

### Tailscale version

Version 1.90.4-t0d7298602-g92f2bb273  com.tailscale.ipn versionCode 496  targetSdk 35 minSdk 26  Installed: 27.10.2025; 13:32 Updated: 02.11.2025; 15:06

### Bug report

BUG-ccf6e55371a2fe52df82eec216ad455859e83f216d52370f522886f84fcd047d-20251102212818Z-e640598131561f82

**Comment by mtzanidakis** [comment]
I have the same issue on my Pixel 6 running stock Android 16 (September 5, 2025 security update) after updating to Tailscale version 1.90.4.

**Comment by Soukyuu** [comment]
For the record, this started happening before 1.90.4, but I can't exactly say which version I was on before

**Comment by Soukyuu** [comment]
I have downgraded to Version 1.88.4-tc18ddfa3d-g4a3522527 on f-droid and the issue is not present. Seems we have our last working veesion.

**Comment by rleeden** [comment]
Same issue started on my Pixel-8 (stock Android 16), I think when upgrading to 1.90.4 - but possibly 1.90.3. And can confirm that disconnecting and reconnecting temporarily fixes the problem. And, also confirm that downgrading to 1.88.4 all works fine again.

**Comment by LukaHummel** [comment]
Can confirm the same problem on my Pixel 8.

**Comment by derFenster** [comment]
Same problem here on a Pixel 8 Pro running Graphene OS Android 16 security update version october 5th 2025. Every version after 1.88.4 has the same issue

**Comment by talyz** [comment]
Same here, on a Galaxy Z Flip 5 running Samsung's stock firmware (Android 16). Downgrading to 1.88.4 seems to have fixed it.

**Comment by quickreactor** [comment]
Same here on Samsung s25

**Comment by stephensrmmartin** [comment]
Confirming. We have two Pixel 7A's. 

My 7A stayed at 1.88.4.
My wife's updated somehow to 1.90.4.

She began experiencing networking issues when switching from wifi to data, or vice versa.
I never had these issues.

I then forced my phone to update to 1.90.4 via Obtainium, and experienced the same problem today when switching from wifi to data.

**Comment by 74wild914** [comment]
Commenting to add that this issue is present on both my Pixel 7 and my wife's Pixel 8 with 1.90.4

**Comment by quagsirus** [comment]
Same issue here on a Pixel 8a and a Pixel 10 (and potentially a MacBook Air M1 when switching networks, although unsure if this is related)

**Comment by Monforton** [comment]
Also experiencing the same issue on a Samsung S23

**Comment by terribilus79** [comment]
Same issue Z Fold7

**Comment by sfllaw** [comment]
Fixed by tailscale/tailscale-android#717 and released as [version 1.90.9](https://tailscale.com/changelog#2025-11-25).

**Comment by Shidapu** [comment]
Still get dns issues with 1.90.9.

**Comment by stephensrmmartin** [comment]
1.90.9 did not fix this for me. I just experienced the issue again after leaving my house and switching to 5g.

**Comment by Rondiniw** [comment]
Having the issue on a Galaxy Fold 7

**Comment by higheraims** [comment]
I'm having this issue on 1.92.3 and GrapheneOS

**Comment by higheraims** [comment]
I thought I solved this by a rollback to 1.88.3 but it has just happened again. Going onto airplane mode + wifi toggle cleared the problem. 

I know this has been closed but it's still an open issue in reality.

It may be an Android change, not a Tailscale one, but still needs fixing.

**Comment by Ellingson** [comment]
Same environment as the original report — GrapheneOS, "Block connections without VPN" off, MagicDNS pointed at a tailnet-IP resolver. I hit this exact symptom (network switch → DNS_PROBE timeouts until I switched back or reconnected the tailnet) consistently through 1.96.4.

It no longer reproduces for me on **1.99.148**: several days of repeated Wi-Fi↔mobile switching and moving between networks, no DNS stalls. The most likely cause is tailscale-android#754 (`bindSocketToNetwork` / `SetAndroidBindToNetworkFunc`), which landed in that window and makes the post-switch socket rebind bind to the live network — consistent with the old "switch back fixes it" behaviour, where each switch just re-fires the rebind. Probably worth others on 1.99+ confirming before this is closed.

One related gap I noticed reading the current source (d8f28f4), a *different* trigger than the Wi-Fi↔mobile case here but the same recovery problem: on Android the only event-driven wake to `netmon` is `InjectEvent` (libtailscale/net.go), reached only via the `onDNSConfigChanged` channel. `NetworkChangeCallback.kt` fires that only inside `if (dns.updateDNSFromNetwork(...))`, which returns true only when the DNS-server string actually changes (DnsConfig.java). `recomputeDefaultNetworkLocked` updates the cached default network but issues no wake, and the `onAvailable` / `onCapabilitiesChanged` callbacks don't touch DNS at all. So a network change that keeps the same DNS — a same-carrier cell-tower handoff, or same-SSID AP roaming — never wakes netmon and gets no rebind until the periodic poll (~10 min). Wi-Fi↔mobile masks it because the DNS server always changes on that transition. Flagging in case it's worth tracking separately.

**Comment by addomam** [comment]
I believe I'm seeing the same issue described here but for disconnecting and reconnecting to the same WiFi network (with no cellular).

I've reproduced it multiple times on a Pixel 9 Pro Fold running GrapheneOS (again, Wi-Fi only, no cellular) while using the current stable Android client (1.98.x).

During the failure:

- The Tailscale app continues to report Connected.
- The app still shows all peers as online.
- Public Internet continues to work.
- Public DNS continues to work.
- Quad100 still resolves public hostnames.
- Every tailnet peer becomes unreachable.
- Every subnet-routed service becomes unreachable.
- Internal split-DNS queries hang.
- Always-on VPN and Block connections without VPN are both disabled.

Restarting only Tailscale does not recover.

Restarting only Wi-Fi does not recover.

The only reliable recovery I've found is:

1. Disable Tailscale.
2. Disable Wi-Fi.
3. Re-enable Wi-Fi.
4. Re-enable Tailscale.

I collected before/after diagnostics and generated bug report: BUG-c0e61070e39b162a349cbc175f00c33fe2387dd0a984128b11355ef4676ee45a-20260727122608Z-ace733873ac3c732

If this is fixed in 1.99 then you can ignore this, I'll validate once it hits the stable branch. Either way my testing confirms @Ellingson's suspicion that this affects more scenarios than originally described and I figured additional diagnostics might be useful regardless.

**Comment by jeremywohl** [comment]
For anyone here whose failure is total (every VPN-covered app loses DNS after a network switch, app still says Connected, only a force-stop or reboot recovers, toggling the VPN in-app does not): I traced that variant with adb and filed it separately as #21155. The distinguishing signature is `netstack inject inbound: write /dev/tun: input/output error` in `logcat -s gojni:*` at the moment of the handoff, after which quad-100 answers nothing and PeerAPI (port 1) times out from peers while WireGuard keeps working. Two quick tests to tell them apart: does 100.100.100.100 answer a query from a shell, and does `curl http://<phone-tailnet-ip>:1/` from a peer respond.

**Comment by OrganicPepper** [comment]
My tailscale seems to be able to recover itself eventually - I only notice the problem if I'm using one of my split DNS services when I have just switched networks (leaving the house, arriving at work etc). If I don't notice it and then try to use my services some hours later (for example, watch a video at lunch at work) connectivity is fine. However, I haven't done rigorous enough testing to know if the bug actually presented in those cases
