### ISSUE TITLE
macOS: Updating Tailscale forces re-login and creates a new device entry instead of reusing existing one

### ISSUE THREAD

**Issue by CatLover01** [tailscale/tailscale#17760]
### What is the issue?

After every Tailscale update on macOS, the app requires a new login. Once logged in again, a new device appears in the Tailscale admin panel instead of reusing the previous device identity.

This creates confusion and clutter, since each update effectively registers the same physical Mac as a new device each time.

### OS

macOS

### OS version

macOS Monterey

**Comment by jager-fools** [comment]
What method was used to install tailscale on the device in question?

https://tailscale.com/kb/1016/install-mac

What version number of macOS Monterey are you running?

**Comment by CatLover01** [comment]
> What method was used to install tailscale on the device in question?
> 
> https://tailscale.com/kb/1016/install-mac
> 
> What version number of macOS Monterey are you running?

Version 12.7.6
If I remember correctly, I installed via the Standalone variant (.pkg)

**Comment by kpowick** [comment]
I'm seeing the same problem with updates.  This is a fairly new issue, so I suspect it's been caused by a recent Tailscale update.

I'm currently running the standalone variant (1.90.6) on macOS 12.7.6 (Intel).  The other (same?) issue is that every time I disconnect, I have to re-login, creating a new device. E.g. device, device-1.

This does **not** happen on my Apple silicon machine running macOS 15.6.1.

**Comment by CatLover01** [comment]
I can confirm that my macOS is also an intel.

**Comment by curtisrempel** [comment]
I can confirm this also happens on Intel MacOS Venture 13.7.8 and Tailscale 1.90.6

**Comment by samueldamon** [comment]
Also happening on Intel MacOS 13.7.6 and Tailscale 1.90.6.

It looks like this bug was introduced in 1.90.1. Reverting to 1.88.4 restores the expected behavior.

**Comment by SpaceSaver** [comment]
I experienced what I believe to be the same bug with the same workaround, but the VPN would never fully connect and turning off and on the client would trigger a reauth

**Comment by nullx8** [comment]
same here running Intel Metal with 13.7.4 and Standalone tailscale 1.91.44
everything besides the re-creation of the existing device when authenticate works perfectly fine.

**Comment by fransimo** [comment]
Same on 1.90.6, macOS 12.7.6 and in my case after reboot it happens again and again.

**Comment by gonzalovlchz** [comment]
Same on Intel Ventura 13.7.8 Tailscale 1.90.6

**Comment by seedubs** [comment]
Same on Monterey 12.6, TailScale 1.90.6. Reverted to 1.88.2 which works as expected.

**Comment by curtisrempel** [comment]
Confirmed: reverting to 1.88.2 works correctly again on Intel Ventura 13.7.8

**Comment by MikeApostol** [comment]
Same issue with me on macOS Monterey 12.7.4. Will try reverting

**Comment by awly** [comment]
We believe that this issue only affects older macOS versions (before macOS 14). There's a fix in progress, cc @patrickod @barnstar 

If your device is supported, try upgrading macOS to a newer version. If not, you can run `defaults write ~/Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool false` (note: edited from `true` to `false` 🤦 ) which should fix the issue until we get a fixed release out.

**Comment by kpowick** [comment]
>_If not, you can run defaults write ~/Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool true which should fix the issue until we get a fixed release out._

Unfortunately, this temporary fix did not correct the problem for me (TS 1.90.6 / macOS 12.7.6 / Intel).

**Comment by amalbansode** [comment]
Thanks Andrew! `defaults write ~/Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool false` (instead of true) followed by restarting the Tailscale client app fixes it for me.

**Comment by SpaceSaver** [comment]
> Thanks Andrew! `defaults write ~/Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool false` (instead of true) followed by restarting the Tailscale client app fixes it for me.

Works for me on macOS 12.7.6 with client version 1.90.6

**Comment by nullx8** [comment]
>  run `defaults write ~/Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool true` which should fix the issue until we get a fixed release out.

this fixes node-duplication on re-auth on osx 13.7.4 with client 1.91.44 (but all ACL's are removed)
upgrading the client (to 1.91.45 Standalone) resulted in a duplicate being created like before.

**Comment by SpaceSaver** [comment]
> > _If not, you can run defaults write ~/Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool true which should fix the issue until we get a fixed release out._
> 
> Unfortunately, this temporary fix did not correct the problem for me (TS 1.90.6 / macOS 12.7.6 / Intel).

@kpowick Try setting it to false instead of true

**Comment by awly** [comment]
Sorry, yes it's `defaults write ~/Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool false` 🤦 
I edited the original reply too.

**Comment by kpowick** [comment]
@SpaceSaver I've tried both true and false, quitting and restarting the TailScale app each time. I still get the same result. Disconnecting then reconnecting results in "_Needs Authentication_, followed by the login options on my web browser.  Logging in (again!) result in multiple devices:  device-1, device-2, etc.

Some additional diagnostic information.  With the TS app connected and the Preferences Window open to the "Account" information, I can see my `Status` as `Logged in`.  If I disconnect TS, my `Status` remains `Logged in`.  However, when I try to re-connect, my Account information clears, as if no accounts are present, until I complete logging in, via GitHub, in my case.

**Comment by awly** [comment]
@kpowick can you share a [bugreport](https://tailscale.com/kb/1227/bug-report)?

**Comment by SpaceSaver** [comment]
> [@SpaceSaver](https://github.com/SpaceSaver) I've tried both true and false, quitting and restarting the TailScale app each time. I still get the same result. Disconnecting then reconnecting results in "_Needs Authentication_, followed by the login options on my web browser. Logging in (again!) result in multiple devices: device-1, device-2, etc.
> 
> Some additional diagnostic information. With the TS app connected and the Preferences Window open to the "Account" information, I can see my `Status` as `Logged in`. If I disconnect TS, my `Status` remains `Logged in`. However, when I try to re-connect, my Account information clears, as if no accounts are present, until I complete logging in, via GitHub, in my case.

Something I was noticing was that it would sometimes appear to overwrite my settings.  Idk if it was just Xcode plist viewer being weird or what.

**Comment by nullx8** [comment]
> Sorry, yes it's `defaults write ~/Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool false` 🤦 I edited the original reply too.

is there a way to downgrade the client temporary to force a test? i could not find old package for the standalone client anywhere.

EDIT: Never mind, found one, but no dice re-auth removes ACL's / TS-upgrade creates a duplicate node.
OSX 13.7.4 (22H420) on I7 Metal, TS 1.91.65 SL

**Comment by roto31** [comment]
I was having the same issue and came across this thread in the support forums. I appreciate the troubleshooting completed so far. I imagine turning off automatic updates till it is fixed will be the best method going forward till the bug is resolved.

For those looking to the 1.88.2 package for a downgrade, it is here: https://pkgs.tailscale.com/stable/?v=1.88.2

Do a complete uninstall following these instructions: https://tailscale.com/kb/1069/uninstall?tab=macos+%28standalone%29

To make for quick cleanup use this bash script: 

```
#!/bin/bash

echo "Removing Tailscale leftovers…"

# Expand ~ safely
USER_HOME="${HOME}"

# Paths to remove
paths=(
    "$USER_HOME/Library/Application Scripts/*.io.tailscale.ipn.macsys"
    "$USER_HOME/Library/Application Scripts/io.tailscale.ipn.macsys"
    "$USER_HOME/Library/Application Scripts/io.tailscale.ipn.macsys.login-item-helper"
    "$USER_HOME/Library/Application Scripts/io.tailscale.ipn.macsys.share-extension"
    "$USER_HOME/Library/Caches/io.tailscale.ipn.macsys"
    "$USER_HOME/Library/Containers/io.tailscale.ipn.macsys"
    "$USER_HOME/Library/Containers/io.tailscale.ipn.macsys.login-item-helper"
    "$USER_HOME/Library/Containers/io.tailscale.ipn.macsys.share-extension"
    "$USER_HOME/Library/Containers/Tailscale"
    "$USER_HOME/Library/Group Containers/*.io.tailscale.ipn.macsys"
    "$USER_HOME/Library/HTTPStorages/io.tailscale.ipn.macsys"
    "$USER_HOME/Library/Preferences/io.tailscale.ipn.macsys.plist"
    "/Library/Tailscale"
)

for path in "${paths[@]}"; do
    # Expand globs manually
    for target in $(echo $path); do
        if [ -e "$target" ]; then
            echo "→ Removing: $target"
            rm -rf "$target"
        else
            echo "→ Skipping (not found): $target"
        fi
    done
done

echo "Done! Tailscale remnants have been cleaned up." 
```

**Comment by kpowick** [comment]
Update 1.90.8 seems to have resolved this issue for me.  However, there is one workstatoin that I must still test, but don't have access to at the moment.  Fingers crossed.

**Comment by chazchandler** [comment]
The problem persists for me.  I tried 1.90.8 and 1.90.9.  Same issue: requires reauth and creates a new machine.  Intel MBP on Ventura 13.7.8.  Tried downgrading to 1.88.2 in between those two and using the cleanup script above after finding that both the newer version had the same issue.  I'm back on 1.88.2 for now.

**Comment by johnweldon** [comment]
I had the same issue with Monterey - after running `defaults write ~/Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool false` I had to restart it once which prompted a login again, and added a new device, but then when I restarted it a second time it no longer prompted for a login and kept the pre-existing device.

**Comment by kpowick** [comment]
> Update 1.90.8 seems to have resolved this issue for me. However, there is one workstation that I must still test, but don't have access to at the moment. Fingers crossed.

I was finally able to test my one Intel MBP and, sadly, it still fails to reuse the existing device ID.

Disconnecting TS requires logging in again.  And re-connecting generates a new device ID.

This applies to TS 1.90.9 as well.

**Comment by nullx8** [comment]
1.93.26 resolved the duplication issue completely, 
but ACL-Tags are still being removed.

Tested updating to 1.93.26 on macOS 13.7.8 on iMac15,1 (Quad-Core Intel Core i7)

**Comment by Badsheep** [comment]
Hello, what is « ACL-Tags » ? I have same issue here and I’d like to know if I can update.

**Comment by nullx8** [comment]
> Hello, what is « ACL-Tags » ? I have same issue here and I’d like to know if I can update.

with the new version the machine is no longer duplicated, BUT if you have ACL's assigned to it, they will be dropped.

**Comment by Badsheep** [comment]
Ok thanks ! I’ve look in the Tailscale help to understand what ACL is, and I think I don’t use it : I only have one user, on differents machines. Am I right ? And do the auto login work with that version ?

**Comment by melstephens** [comment]
I'm also seeing this on a Windows 11 (23H2) machine - restart the machine and Tailscale no longer logs in automatically. Log in and a new machine is created, same name as the old one with an incrementing number appended.

1.88.1 works
1.90.9 I'm not sure about
1.92.1 definitely has the issue

I think I updated by downloading and running the install but I may have used winget.

I don't use ACL tags.

**Comment by Badsheep** [comment]
Hello, do we know if this bug will be solved ?

**Comment by MikeApostol** [comment]
Same here, hoping to hear if this is fixed yet - I do use Access Controls and don't want to experiment and lose them if it's not solved yet

**Comment by SpaceSaver** [comment]
> Same here, hoping to hear if this is fixed yet - I do use Access Controls and don't want to experiment and lose them if it's not solved yet

The workaround works

**Comment by crispybegs** [comment]
> Sorry, yes it's `defaults write ~/Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool false` 🤦 I edited the original reply too.

this fixed it for me (intel / monterey). thanks, having 18+ 'imac' machines in my admin panel was very annoying

**Comment by juebai** [comment]
Hope this gets fixed with future release.
For Ventura & Monterey it‘s creating duplicates but not for Sonoma & Sequoia. Using standalone package version 1.94.2

**Comment by MikeApostol** [comment]
> Hope this gets fixed with future release. For Ventura & Monterey it‘s creating duplicates but not for Sonoma & Sequoia. Using standalone package version 1.94.2

The suggested fix worked with my Mac OS Monteray: defaults write ~/Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool false

**Comment by juebai** [comment]
Thank you. Worked for me, too 🤗Am 26.02.2026 um 15:21 schrieb MikeApostol ***@***.***>:﻿MikeApostol left a comment (tailscale/tailscale#17760)

Hope this gets fixed with future release. For Ventura & Monterey it‘s creating duplicates but not for Sonoma & Sequoia. Using standalone package version 1.94.2

The suggested fix worked with my Mac OS Monteray: defaults write ~/Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool false

**Comment by Schwefelholz** [comment]
Same for me on Monterey 12.7.6:
`defaults write ~/Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool false`
Resolved the issue for the current stable client 1.96.2

**Comment by fortydegrees** [comment]
Seeing the same issue on an Intel MacBook Pro running macOS 13.1 with Tailscale 1.98.5.

After updating Tailscale, it required re-authentication and registered the same physical Mac as a new machine with a new 100.x address, leaving the previous admin-console machine entry stale/dead. Disabling key expiry on the old machine didn't prevent this.

I then ran:

`defaults write ~/Library/Preferences/io.tailscale.ipn.macsys.plist EncryptState -bool false`
`killall cfprefsd`

Confirmed `EncryptState` reads `0`.

After that, the first re-auth still created one new machine entry, presumably because the previous local state was already lost. But after keeping the newest entry, quitting/restarting Tailscale and using “renew session” no longer created further duplicate machines.

So the workaround appears to prevent future duplicates on 1.98.5/macOS 13.1, but doesn't attach back to the already-existing stale machine entry once the local state has been lost.

**Comment by tombo9999** [comment]
As of today Tailscale for macOS version 1.98.8 standalone variant on iMac (Retina 4K, 21.5-inch, Late 2015) and macOS Monterey 12.7.6
Same issue, the workaround resolved the issue, but :/

**Comment by Strajevski** [comment]
apparently this will be fixed in "the next release" (as of a week ago) - this is still occurring on 1.98.10 macOS 13.6.6 (standalone, not app store)

**Comment by barnstar** [comment]
I can confirm that this should be resolved in the 1.102.x release which is available as a release-candidate here: https://pkgs.tailscale.com/release-candidate/

The workaround above (setting the EncryptState default to 0) will also fix it for older versions.

**Comment by nickoneill** [comment]
1.102 is released with this fix
