### ISSUE TITLE
Tailscale GUI won't disconnect on macOS.

### ISSUE THREAD

**Issue by ilium007** [tailscale/tailscale#17928]
### What is the issue?

When disconnecting via the UI the 'connected' slider bouncers between disconnected and connected and returns to being connected. If I issue `tailscale down` in the CLI it does disconnect and is reflected in the UI.

### Steps to reproduce

Connect UI and attempt to disconnect

### Are there any recent changes that introduced the issue?

No - the client did auto update recently but unsure if this was happening in last version. I certainly didnt notice until this update.

### OS

macOS

### OS version

15.5.0

### Tailscale version

1.90.6

### Bug report

BUG-acf82732d2ed73c17170625c373b962b3eb8747400f6ae09ecedac3ba1b3b258-20251116015724Z-e82755741dca03f4

**Comment by ilium007** [comment]
I do have a screen recording I can share privately if required.

**Comment by luckman212** [comment]
I've experienced this with Tailscale (and other VPNs) when VoD is enabled

<img width="600" height="580" alt="Image" src="https://github.com/user-attachments/assets/1b1f3588-3b4c-4c78-b823-508be711d556" />

<img width="604" height="317" alt="Image" src="https://github.com/user-attachments/assets/17ecd150-b00a-48e4-a483-35ced9c5b12e" />

**Comment by ilium007** [comment]
VoD was enabled but with Wifi SSID exceptions for my home network in place. This is how I've always had it set up. Disabling VoD resolves the issue.

**Comment by croakerbcts** [comment]
Hi @ilium007  we believe this should be resolved in 1.96.5 - could you review and let us know? Thanks!

**Comment by thecoolwinter** [comment]
@croakerbcts still an issue in 1.96.5 I'm afraid. Really annoying :(

https://github.com/user-attachments/assets/ca5744b5-8ce6-4c1a-93de-d9f6c5fdb1dc
