### ISSUE TITLE
dns-forward-failing health warning appears even when performing valid DNS queries

### ISSUE THREAD

**Issue by luckman212** [tailscale/tailscale#18146]
### Bug

With MagicDNS disabled, even just a single DNS query directed towards 100.100.100.100 will result in the healthcheck warning below, which appears and never goes away:

_"Tailscale can't reach the configured DNS servers. Internet connectivity may be affected."_

I've been reporting this bug since around **March 2025**. When I reported #18101, I originally thought the bug only occurred when _invalid_ DNS queries were passed to `100.100.100.100`. But, further testing (as in the repro script below) revealed that **even valid, successful queries will trigger it**.

### Previous reports

- [TSS-68644](https://tailscale.atlassian.net/servicedesk/customer/portal/1/TSS-68644)
- #18101
- #15389

> there are also many other similar or identical reports e.g. #13520, #13461, #13235, #12244

##### Menubar icon
<img width="66" height="56" alt="Image" src="https://github.com/user-attachments/assets/15cb809c-30d9-4242-979e-3c92a50d5681" />

##### Main UI
<img width="1780" height="1104" alt="Image" src="https://github.com/user-attachments/assets/d634b6b6-0ec6-4f8c-b7ea-c30cd0e3b056" />

##### Debug window
<img width="450" height="375" alt="Image" src="https://github.com/user-attachments/assets/092c76cf-8aa4-4897-ad5b-3137b736f420" />

### Steps to reproduce

This occurs when "MagicDNS" is not enabled on the client. I have a _very_ simple and easy repro for it that I tested on a **brand new** macOS 26.1 virtual machine with nothing else done other than:

1. Install macOS
2. Log in
3. Install Tailscale (tested with both release 1.90.9 and unstable 1.93.28)
4. Join tailnet
5. Configure settings as shown in the screenshot below
6. Install the `tailscale` CLI tool (Settings → CLI integration)
7. Run my [`tsbug`](https://gist.github.com/luckman212/356dfc72396b838a055ec10d315b042b) (gist) zsh script which:
    - installs a DNS resolver override for your tailnet pointing at quad100
    - selects a random peer from your Tailnet
    - performs a DNS query of that peer using dscacheutil
    - pauses for 1 second
    - repeat

This reproduces the issue 100% of the time after 15 seconds. The bug occurs whether you use `8.8.8.8/1.1.1.1` as your DNS server, or the typical DHCP-assigned LAN server.

#### Steps to run repro script

Copy & paste the block below into a Terminal:
```shell
curl -Lso tsbug https://gist.github.com/luckman212/356dfc72396b838a055ec10d315b042b/raw && chmod +x tsbug
./tsbug
```

### Screen Recordings

I made 2 screen recordings of this, one from the VM:

https://github.com/user-attachments/assets/f44431b8-c187-487b-bde5-abc076e2e736

And one from earlier on my physical Mac (before I created the repro script, but essentially the identical test). The terminal windows below are:

- top: ping to `8.8.8.8` to show stable connectivity
- middle, left: DNS lookup (dig) of `tailscale.com` to show working DNS
- middle, right: tailscaled health status via `tailscale status --json`
- bottom: repro script running sequential DNS queries of host in my tailnet

https://github.com/user-attachments/assets/9cbbb49f-de78-4ef7-ac4c-87820d4c57bf

### Tailscale Settings used for reproduction

<img width="600" height="580" alt="Image" src="https://github.com/user-attachments/assets/3f144d2e-0ddb-4bf8-a7d9-b003dc99d921" />

### OS

- macOS 15.6.1, 26.1, 26.2
- FreeBSD 16-CURRENT

### Tailscale versions affected/confirmed

- 1.93.82 unstable
- 1.92.3 stable
- all other prior versions (both stable and unstable) released since 2025-03

[TSS-68644]: https://tailscale.atlassian.net/browse/TSS-68644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by luckman212** [comment]
ping @barnstar since you were listed as the assignee on the old bugreport of this same issue, and @nickoneill since you participated in past discussions as well.

Happy to provide any further logs, device access or literally anything else to get this fixed. Thank you 🙏

**Comment by luckman212** [comment]
Here's some output from `tailscale debug daemon-logs`, executed just before triggering this failure:

```
[logtap connected]
dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
health(warnable=dns-forward-failing): error: Tailscale can't reach the configured DNS servers. Internet connectivity may be affected.
health: connectivity impacted; triggering captive portal detection
gui: Adding health warning: dns-forward-failing
DetectCaptivePortal(found=false)
Received error: PollNetMap: unexpected EOF
control: sockstats: trace "ControlClientAuto" was overwritten by another
control: controlhttp: forcing port 443 dial due to recent noise dial
control: netmap: got new dial plan from control
```

**Comment by luckman212** [comment]
In order to rule out this being caused by some odd setting in my Tailnet, I:

- created a completely NEW Tailscale acocunt & tailnet
- created 2 new macOS 15.6.1 VMs
- installed Tailscale 1.90.9 pkg version on each of them
- disabled MagicDNS in the app Settings (not on the Tailnet itself)
- ran the tsbug script above

The bug was easily reproduced.

**Comment by luckman212** [comment]
Adding some information that may aid in debugging.

In my testing, _after_ reproducing this bug, if you:

- toggle Tailscale OFF from the menubar icon
- wait for the connection to be fully torn down
- turn the toggle back ON

...then Tailscale appears to enter a state which makes reproducing the bug either impossible, or at least much more difficult. I don't know what it is about tearing down the connection and re-establishing it that "fixes" this. Some sort of timing issue, or interface metric/priority?

**Comment by nickoneill** [comment]
We'll suppress this healthcheck warning when magicdns is off in an upcoming release. I'll ping here when we have an unstable with this for you to check

**Comment by smonode** [comment]
Everyone, I'm experiencing the same behaviour in a slightly different scenario. Happy to share my insights as this might be related to this issue and could help figuring out the details.

I'm using Tailscale on macOS parallel to iCloud Private Relay which works just fine (nowadays). The only issue on macOS is (in contrast to iOS where a single DNS pipeline is being used), that Safari seems not to use iCloud Private Relay for DNS resolution but only internet traffic.

Long story short, many testings and research showed that this is due to the fact, that tailscale registers the search domain of my tailet for easy host name resolution. This lets macOS / Safari use the local DNS server instead of their ODoH implementation.

The workaround is simple: Disable Tailscale MagicDNS in the macOS client and manually configure the tailet domain without using a search domain:

```
sudo mkdir -p /etc/resolver
sudo sh -c 'echo "nameserver 100.100.100.100" > /etc/resolver/tailXXXXXX.ts.net'
sudo dscacheutil -flushcache
sudo killall -HUP mDNSResponder
```

This works like a charm with two downsides:

* Always have to use FQDN instead of hostname (obviously)
* The warning *dns-forward-failing* is being displayed in the macOS menu bar

It would be great to see an option in Tailscale (either globally or in the client) *not* to use a search domain (in favour of enabling DNS resolution through iCloud Private Relay).

... and of course the *dns-forward-failing* error bugs me as everything is working just fine.

For reference:
* macOS 26.2 (25C56)
* Tailscale App Store version (1.92.3)
* Safari Version 26.2 (21623.1.14.11.9)

**Comment by luckman212** [comment]
Greetings @swehrli — nice to finally find another person on the planet who is affected by this. It was getting pretty lonely in here!

Looks like as I was typing this @barnstar closed it. Don't see the commit yet so I guess it's an internal fix that hopefully shows up in unstable shortly.

As far as the drawback of _"always have to use FQDN"_ instead of just `ping harry` etc, my workaround for that is using `/etc/hosts` where you can define whatever custom hostnames you want and point them at your Tailnet devices.

Here's a 1-liner to automatically generate entries for all devices in your tailnet, the output of which you can copy+paste into `/etc/hosts`

```
tailscale status --json | jq -r '.Peer | map(select(.HostName!="funnel-ingress-node")) | sort_by(.HostName)[] | "\(.TailscaleIPs[0])\t\(.HostName|ascii_downcase)"'
```

**Comment by luckman212** [comment]
@barnstar Thanks for the progress, but this isn't quite solved.

I installed 1.94.0 rc and while the menubar icon no longer shows the warning, the healthcheck is still "failing" according to Tailscale's internal status:

```
$ tailscale status --json | jq -r '.Health'
[
  "Tailscale can't reach the configured DNS servers. Internet connectivity may be affected."
]
```

```
$ tsbug
elapsed: [  0s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
elapsed: [  1s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
elapsed: [  2s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
elapsed: [  3s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
elapsed: [  4s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
elapsed: [  5s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
elapsed: [  6s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
elapsed: [  7s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
elapsed: [  8s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
elapsed: [  9s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
elapsed: [ 10s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
elapsed: [ 11s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
elapsed: [ 12s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
elapsed: [ 14s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
Tailscale can't reach the configured DNS servers. Internet connectivity may be affected.
elapsed: [ 15s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
Tailscale can't reach the configured DNS servers. Internet connectivity may be affected.
elapsed: [ 16s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
Tailscale can't reach the configured DNS servers. Internet connectivity may be affected.
elapsed: [ 17s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
Tailscale can't reach the configured DNS servers. Internet connectivity may be affected.
elapsed: [ 18s]  querying pdm.yak-stargazer.ts.net using dscacheutil: ip_address: 100.69.153.96
^C
```

**Comment by nickoneill** [comment]
@luckman212 We made a decision to suppress the health warning in the UI when magicDNS is off as opposed to adjusting the triggers for the health warning itself (imo the warning is reporting correctly, if you're not using magicDNS then resolving against 100x4 has no meaningful response). Does this configuration not resolve your needs?

**Comment by luckman212** [comment]
Thanks but no, this does not resolve this issue @barnstar @nickoneill 

***I definitely do have MagicDNS enabled*** for my Tailnet. What I am NOT using is the "Use Tailscale DNS" setting below

<img width="547" height="141" alt="Image" src="https://github.com/user-attachments/assets/e5a9f300-3de9-4569-87a7-5cf11a9d3a48" />

Instead, I'm routing requests for `*.ts.net` to 100.100.100.100 using a DNS override at `/etc/resolver/yak-stargazer.ts.net`, the contents of which are

```
nameserver 100.100.100.100
```

**Comment by luckman212** [comment]
@nickoneill @barnstar 

I drew a rough flowchart of what the DNS healthcheck should be doing in my mind. I'm in the middle of a busy day so definitely could be errors in this logic but I wanted to put this thought down:

<img width="755" height="766" alt="Image" src="https://github.com/user-attachments/assets/e7c754b8-ae76-4d07-84f7-deae1acad530" />

**Comment by lmagyar** [comment]
To add insult to the injury, this SERVFAIL is "provoked" by Tailscale itself in each hour when `accept_dns` is disabled!

I've made some experiment, I've put a dnsmasq proxy in front of 100.100.100.100, plus with iptables black magic any query directed to 100.100.100.100 went through this proxy, and there were nothing directed to 100.100.100.100 (nothing logged by the dnsmasq proxy), but in each hour there were these lines in the logs:

```
2026/01/18 08:44:31 [RATELIMIT] format("dns: resolver: forward: no upstream resolvers set, returning SERVFAIL") (1 dropped)
2026/01/18 08:44:31 dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
2026/01/18 08:44:31 dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
2026/01/18 08:44:31 dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
2026/01/18 08:44:31 dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
2026/01/18 08:44:31 dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
2026/01/18 08:44:31 [RATELIMIT] format("dns: resolver: forward: no upstream resolvers set, returning SERVFAIL")
```

I've tried to search for (in my LAN routers logs), what TS queried at this time (I assume after 100.100.100.100 weren't able to answer, the query, it went through the normal OS resolv.conf "path"), but couldn't figure out.

TLDR: Without any external query, when `accept_dns` is disabled, TS "provokes" these log lines and health state on it's own in each hour also.

**Comment by zapovit** [comment]
I am also facing this issue for some weeks now with a Tailnet client who acts as DNS server for the rest of the mesh network. 

Since I own the DNS server I am able to confirm that the queries are coming through fine. The DNS server does not accept Tailscale DNS settings for what I hope are obvious reasons. The next time I notice it I will generate a bug report ID and paste it here.

**Comment by zapovit** [comment]
Captured two bug id's today while receiving this bunk "dns unreachable" message...

* bug report id from client with --accept-dns=true set on Tailscale dns server: BUG-32e299da915cca24c753fded6fc0578ff86cb68cc53a328dbed52ebec0dd3528-20260125010818Z-2d50a5aa98313666
* bug report id from client with --accept-dns=false set on Tailscale dns server: BUG-32e299da915cca24c753fded6fc0578ff86cb68cc53a328dbed52ebec0dd3528-20260125034636Z-c240a1de9ee50a0e

Therefore I am not sure accept-dns is implicated. Or I just happen to have a misconfiguration that surfaces this message ~ 1 hour after connecting to the tailnet. To reiterate, dns queries are being received by my tailnet dns server without issue, no immediately obvious network issues observed. 

Regards,
zapovit

**Comment by luckman212** [comment]
@zapovit this issue is closed, please continue at #18436 - although I don't know if there's anything more to add. Tailscale devs know about the issue now and I think we just have to wait for a fix.

**Comment by zapovit** [comment]
Thanks for the heads up, and thanks for pursuing this this bug for so long!

**Comment by zapovit** [comment]
@barnstar it seems the fix is not actually working in the case of specifying a tailnet client as a DNS server... 

<img width="213" height="464" alt="Image" src="https://github.com/user-attachments/assets/ab402ef0-dcbe-435a-9ea8-a59c39622b0c" />

<img width="4320" height="3316" alt="Image" src="https://github.com/user-attachments/assets/5df35ab6-a326-4df8-9b2c-a810be3a96ad" />

**Comment by wickedyoda** [comment]
Still not working, constantly getting this on my pixel 9xl phone and macbook mini. Neither are DNS servers, but just clients.

**Comment by zapovit** [comment]
Same here but I do run my own dns server. I am also getting the odd network hang now. It's a shame this is broken because it seems like an obvious configuration. 

BUG-140fb98f0d426919f1567554f1e19571faa6e69d2fd7ce34a2172a23e76291b7-20260620014441Z-3ac25f9daa5cc87f

**Comment by eddiem5** [comment]
I ran into what might be a related root cause while running Pi-hole/unbound as my tailnet's DNS server (configured via "Override DNS servers" / Global Nameservers in the admin console — a plain custom resolver, not Tailscale's own MagicDNS backend as the actual upstream).

**Symptom:** one of my nodes was periodically tripping Pi-hole's built-in per-client rate limiter (1000 queries/60s). Looking at the query log showed a very specific pattern: an AAAA query for the node's own hostname (both the bare form, e.g. `my-node`, and the `.lan`-qualified form, e.g. `my-node.lan`) arriving every exactly 10 seconds, indefinitely, and always failing (NXDOMAIN/NODATA) — because Pi-hole (a plain custom DNS server with no built-in knowledge of tailnet device names) had no record for that hostname.

**Root cause, confirmed via `strace`:** I attached `strace -f -e trace=network` across every long-lived process on the box, and correlated stray thread/child-process IDs back to their owning process via `/proc/<pid>/status` (`Tgid`/`PPid`). This confirmed `tailscaled` itself (PID matched directly in one capture, plus short-lived child processes it spawns for others) is the one issuing this query, sent directly to the configured upstream DNS server (in my case `100.104.180.26:53`, my Pi-hole box) — not any application running on the node.

**The fix, and why it points at a gap:** once I added a manual Local DNS Record on Pi-hole mapping the node's Tailscale IPv6 address to its own hostname (both the bare and `.lan`-qualified forms), the exact same query started resolving successfully (`reply=IP`) instead of failing — same 10-second cadence, just now succeeding. So my fix was simple, but it suggests: **if a tailnet is configured with a custom override DNS server that isn't Tailscale-aware, `tailscaled`'s own periodic self-check query for the node's own hostname has no way to succeed unless the admin manually adds that mapping on the custom server** — which isn't documented anywhere I could find, and isn't something an admin would think to add since every *other* domain resolves fine through that same server.

This might explain part of why `dns-forward-failing` (or the general DNS health signal) behaves inconsistently for people running custom upstream DNS: the check itself depends on a record most custom DNS setups won't have, through no fault of the actual DNS forwarding path.

**Environment:**
- tailscaled 1.98.9 (`4fb758c39ae5b208b974af14ba6bc896a250394c`)
- Linux (Raspberry Pi OS / Debian, aarch64)
- Custom DNS server: Pi-hole Core v6.4.3 + unbound (recursive resolver), reached via Tailscale's "Override DNS servers" global nameserver setting

Happy to share the exact `strace` output / Pi-hole query log excerpts if useful for reproducing.

**Comment by jedinjapan** [comment]
> **The fix, and why it points at a gap:** once I added a manual Local DNS Record on Pi-hole mapping the node's Tailscale IPv6 address to its own hostname (both the bare and `.lan`-qualified forms), the exact same query started resolving successfully (`reply=IP`) instead of failing — same 10-second cadence, just now succeeding. So my fix was simple, but it suggests: **if a tailnet is configured with a custom override DNS server that isn't Tailscale-aware, `tailscaled`'s own periodic self-check query for the node's own hostname has no way to succeed unless the admin manually adds that mapping on the custom server** — which isn't documented anywhere I could find, and isn't something an admin would think to add since every _other_ domain resolves fine through that same server.
> 
> This might explain part of why `dns-forward-failing` (or the general DNS health signal) behaves inconsistently for people running custom upstream DNS: the check itself depends on a record most custom DNS setups won't have, through no fault of the actual DNS forwarding path.

This is absolutely brilliant work and I've implemented this possible fix on my Pi-hole DNS resolver as well. I'll be doing some spot testing to see if I can reproduce the error next time I'm on a remote network, as this issue doesn't occur for me when on the home network.

Hopefully Tailscale can flag the node's machine name self-health check to be disabled when the user has elected to use a custom DNS resolver, or add similar detail to your report here to the custom DNS section of the documentation.

**Comment by zapovit** [comment]
I don't think the issue of tailscaled looking up the node's own hostname is relevant for the following reason: I use 100.100.100.100 as a backend for all *.ts.net dns lookups. Still, the issue persists. 

I also run a healthcheck on the tailscale container per official examples (sidecar configuration), upon which the dns container (adguard home) depends. Adguard home, in my installation, uses the tailscale container's network interface directly (i.e. not 0.0.0.0 but 100.xxx.xxx.xxx).
