### ISSUE TITLE
Can't activate/login Synology

### ISSUE THREAD

**Issue by xerxesb** [tailscale/tailscale#2988]
I was configuring 2 Synology NAS's today. An one based on Intel (DS720+) and another based on ARM (DS216j).

The package downloaded and installed on both devices.
When activating the installation on the DS720:
1. I clicked "Open" in the Package Manager. 
2. It opens a new tab saying "Redirecting with session token..."
3. It redirected to a page with the text "Login. Get started by logging in to your Tailscale network. Or, learn more at tailscale.com.", and has a blue "Log in" button.
4. I clicked "Log in", and went through to authorise Tailscsale on my account.
Success.

When activating the installation on the DS216j:
1. I clicked "Open" in the Package Manager. 
2. It opens a new tab saying "Redirecting with session token..."
3. It redirected to a page with the text "Login. Get started by logging in to your Tailscale network. Or, learn more at tailscale.com.", and has a blue "Log in" button.
4. I clicked "Log in", and nothing happens.

I've tried different browsers and different variations of opening the tab, but it always just takes me to the same "Login. Get started by..." screen without progressing.

I've looked at the Network inspector when clicking the button and I can see that it is sending a POST to the following endpoint (http://<SERVER_URL>:5000/webman/3rdparty/Tailscale/?up=true&SynoToken=lpwgTX9ejyAx6), but the response is never received. The Response section of the network request just shows a spinner.

Here is the output from the network inspector in Safari
```
Summary
URL: http://<SERVER_URL>:5000/webman/3rdparty/Tailscale/?up=true&SynoToken=TfUmuzghi46tQ
Status: —
Source: —
Initiator: 
Tailscale:1408


Request
Accept: application/json
Content-Type: application/json
Referer: http://<SERVER_URL>:5000/webman/3rdparty/Tailscale/?SynoToken=TfUmuzghi46tQ
Origin: http://<SERVER_URL>:5000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15

Response
<SPINNER>

Query String Parameters
up: true
SynoToken: TfUmuzghi46tQ
```

I'm leading to believe the issue is specific to the ARM build as my installation on the Intel Synology went flawlessly.

**Comment by ktnakane** [comment]
I had the same problem.
But, This was successful.

Log in with ssh and go to "/ var / packages / Tailscale / etc". Execute "tailscale up".
Then, access the displayed url with a browser.

**Comment by Heliosmaster** [comment]
I don't think this is ARM specific. The tailscale daemon seems to not be always up. If I click on the tailscale package from the dashboard I'm getting what you are reporting.
 I need to go to the package manager, see Tailscale and then the "Run" button appears. Other _service components_ are automatically started and i get the "Open" button instead.
If I click on Run it starts and then I can access the admin console and login.

**Comment by Grovespaz** [comment]
I have the same issue (and seems to be a dupe of #4648), it's possible to manually trigger the login flow by executing
```
data.Reauthenticate = true;
postData(e);
```
in the right scope in the browser development tools, but after the login is successful (and the web UI on the NAS confirms so) Tailscale still won't come up. Re-opening the tailscale web ui just brings us back to the same login page. This may be a separate issue.

**Comment by DentonGentry** [comment]
The next time someone sees this happening, could you check the permissions on /dev/net? It should be 755:
```
admin@dsm7:/$ ls -ld /dev/net
drwxr-xr-x 2 root root 60 Jun 4 19:43 /dev/net
```

**Comment by xxtro** [comment]
I'm having this issue and the permissions on /dev/net are 755.

**Comment by DentonGentry** [comment]
I think most of these symptoms were resolved by https://github.com/tailscale/tailscale/pull/5395 in Tailscale 1.30.0 and later.

@xxtro if you see it again please file a new bug, and if possible SSH to the synology to run "tailscale bugreport" and include the string it prints. If you can't get a bugreport, please include the Tailscale IP address of the Synology and as exact a timestamp as you can (with timezone you are in).

**Comment by miglesias** [comment]
> I had the same problem. But, This was successful.
> 
> Log in with ssh and go to "/ var / packages / Tailscale / etc". Execute "tailscale up". Then, access the displayed url with a browser.

Thank you for this post. I am on 1.30.2-300027 and was still receiving the same thing after an update as well as an uninstall/reinstall.
