### ISSUE TITLE
"Page not found..." on Synology with Tailscale 1.12.4

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2996]
Tailscale failed to load the login page on Synology DSM7/DSM6 with Tailscale 1.12.4 

![image](https://user-images.githubusercontent.com/75628398/136086822-ea4f97bb-57c0-42c6-8a70-0f880c34f1ab.png)

![image](https://user-images.githubusercontent.com/75628398/136086986-e4e9df64-cace-4b78-a86e-b4acc14ecacf.png)

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3mz9t)

**Comment by maisem** [comment]
I'm seeing this when I updated my synology build to 1.15.217.

**Comment by maisem** [comment]
fyi @DentonGentry

**Comment by paullesiak** [comment]
Actually still seeing this issue, running the latest 1.16.0 from the [tailscale-synology repo](https://github.com/tailscale/tailscale-synology/releases/tag/v1.16.0)

**Comment by DentonGentry** [comment]
I think this is resolved by finding the path to use.
Barring further comments, we'll expect to close this during the next bug scrub.

**Comment by ckambler** [comment]
i just updated to the latest version from github (hasn't shown up yet on the synology package center), version 1.16.2, still seeing the same error. i first uninstalled the old tailscale, then rebooted the NAS, and installed the new package. I saw a comment above about "appdata" and "appstore" being a change with the DSM7 upgrade, is there some kind of leftover folder or file cleaning i need to do after uninstalling the old version to get the new one to work correctly?

**Comment by maisem** [comment]
@ckambler are you on dsm7?

**Comment by ckambler** [comment]
> I fixed this by removing `/var/packages/Tailscale/etc/tailscaled.sock` and replacing it with a symbolic link to `/volume1/@appdata/Tailscale/tailscaled.sock`, e.g.:
> 
> ```shell
> ssh <user>@<synology>
> sudo rm /var/packages/Tailscale/etc/tailscaled.sock
> sudo ln -s /volume1/@appdata/Tailscale/tailscaled.sock /var/packages/Tailscale/etc/tailscaled.sock
> ```
> 
> Then then "Open" link in package manager works. I guess this was a stale file/configuration from before this system was running DSM 7. On a side note, I just set up a DS220+ that came pre-installed with DSM 7, and the tailscale package installed and ran with no issues.

just tried this, it worked for me! not sure what the permanent fix is without SSH'ing in, but at least for me the problem is resolved.

**Comment by ckambler** [comment]
> I fixed this by removing `/var/packages/Tailscale/etc/tailscaled.sock` and replacing it with a symbolic link to `/volume1/@appdata/Tailscale/tailscaled.sock`, e.g.:
> 
> ```shell
> ssh <user>@<synology>
> sudo rm /var/packages/Tailscale/etc/tailscaled.sock
> sudo ln -s /volume1/@appdata/Tailscale/tailscaled.sock /var/packages/Tailscale/etc/tailscaled.sock
> ```
> 
> Then then "Open" link in package manager works. I guess this was a stale file/configuration from before this system was running DSM 7. On a side note, I just set up a DS220+ that came pre-installed with DSM 7, and the tailscale package installed and ran with no issues.

your solution of creating a symlink from the appdata folder made me think maybe it wasn't getting scrubbed when i uninstalled the app. i uninstalled, deleted the remnant folder, and reinstalled. everything works now!

**Comment by DentonGentry** [comment]
I think this is working now.

**Comment by tetienne** [comment]
Hi, I faced exactly the same issue running the latest published version or with the 1.28.
My DS1816+ is running DSM 7 update 3.
