### ISSUE TITLE
Decide on, clean up redundant labels

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3040]
What's up with the "fr" label?

And how's it related to our existing labels?

Seems like we now have 3 ways to say "feature request". I thought two was a lot.

/cc @mayakacz @DentonGentry

**Comment by DentonGentry** [comment]
I think this is resolved.

**Comment by bradfitz** [comment]
I still see "fr" and "enhancement" as labels. How was that resolved? They look redundant.

**Comment by mayakacz** [comment]
I have not spent any time on this yet, apologies.
