### ISSUE TITLE
meta: run Windows tests on actual Windows VMs

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#50]
We don't currently run the GitHub actions on Windows VMs. We currently just cross-compile things.

But GitHub doesn't charge extra for Windows (like they do for macOS), so just use Windows and then actually run the tests.

**Comment by bradfitz** [comment]
@alexbrainman, do you know how to set up GitHub Actions to make this repo run its tests on Windows?

**Comment by alexbrainman** [comment]
> @alexbrainman, do you know how to set up GitHub Actions to make this repo run its tests on Windows?

I do not know. I read couple of articles before about it. I don't think it will be hard. I can, probably, copy most of your Linux GitHub Actions file. Do you want me to try?

Alex

**Comment by bradfitz** [comment]
Go for it.

**Comment by bradfitz** [comment]
@alexbrainman, most of the work here will be making our existing tests pass. The GitHub actions yaml is as simple as turning "ubuntu-latest" into "windows-latest":

https://github.com/tailscale/tailscale/pull/819/commits/fac520b10a837231ec013d5cde95b60368e1c5b0

But gotta fix all those failures before it can be merged:

https://github.com/tailscale/tailscale/pull/819

**Comment by alexbrainman** [comment]
> But gotta fix all those failures before it can be merged:

I saw you started fixing some tests.

I also tried to debug net/netcheck.TestBasic. With this diff

```
diff --git a/net/netcheck/netcheck.go b/net/netcheck/netcheck.go
index 8433d1d..2e98924 100644
--- a/net/netcheck/netcheck.go
+++ b/net/netcheck/netcheck.go
@@ -467,8 +467,10 @@ func (c *Client) readPackets(ctx context.Context, pc net.PacketConn) {
        var buf [64 << 10]byte
        for {
                n, addr, err := pc.ReadFrom(buf[:])
+               fmt.Printf("READ: n=%v addr=%v err=%v\n", n, addr, err)
                if err != nil {
                        if ctx.Err() != nil {
+                               fmt.Printf("REA_: err=%v\n", ctx.Err())
                                return
                        }
                        c.logf("ReadFrom: %v", err)
@@ -1173,7 +1175,8 @@ func (rs *reportState) runProbe(ctx context.Context, dm *tailcfg.DERPMap, probe
 
        switch probe.proto {
        case probeIPv4:
-               rs.pc4.WriteTo(req, addr)
+               n, err := rs.pc4.WriteTo(req, addr)
+               fmt.Printf("WRITE: n=%v err=%v\n", n, err)
        case probeIPv6:
                rs.pc6.WriteTo(req, addr)
        default:
```

I can see this on windows

```
WRITE: n=0 err=write udp4 0.0.0.0:52655->127.0.0.1:52653: wsasendto: The requested address is not valid in its context.
WRITE: n=0 err=write udp4 0.0.0.0:52655->127.0.0.1:52653: wsasendto: The requested address is not valid in its context.
WRITE: n=0 err=write udp4 0.0.0.0:52655->127.0.0.1:52653: wsasendto: The requested address is not valid in its context.
READ: n=0 addr=<nil> err=read udp4 0.0.0.0:52655: use of closed network connection
REA_: err=context deadline exceeded
--- FAIL: TestBasic (1.00s)
    netcheck.go:185: probePortMapServices: me 192.168.56.1 -> gw 192.168.1.1
    netcheck.go:185: udp=false v4=false v6=false mapvarydest= hair= portmap=U derp=0
    netcheck_test.go:64: want UDP
    netcheck_test.go:67: expected 1 key in DERPLatency; got map[]
    netcheck_test.go:70: expected key 1 in DERPLatency; got map[]
    netcheck_test.go:73: expected GlobalV4 set
    netcheck_test.go:76: PreferredDERP = 0; want 1
    stuntest.go:63: STUN server shutdown
WRITE: n=0 err=write udp4 0.0.0.0:52659->127.0.0.1:52657: wsasendto: The requested address is not valid in its context.
WRITE: n=0 err=write udp4 0.0.0.0:52659->127.0.0.1:52657: wsasendto: The requested address is not valid in its context.
READ: n=0 addr=<nil> err=read udp4 0.0.0.0:52659: use of closed network connection
REA_: err=context deadline exceeded
FAIL
FAIL    tailscale.com/net/netcheck      1.309s
FAIL
```

and this on linux

```
=== RUN   TestBasic
WRITE: n=40 err=<nil>
READ: n=32 addr=127.0.0.1:44589 err=<nil>
READ: n=40 addr=127.0.0.1:37204 err=<nil>
    netcheck.go:185: probePortMapServices: me 192.168.1.27 -> gw 192.168.1.1
    netcheck.go:185: udp=true v6=false mapvarydest= hair=true portmap=U v4a=127.0.0.1:60230 derp=1 derpdist=1v4:0s
    stuntest.go:63: STUN server shutdown
--- PASS: TestBasic (0.10s)
PASS
ok      tailscale.com/net/netcheck      0.106s
```

Feel free to fix it, if you know what the problem is. But I will continue my debug, if I don't hear from you.

Alex

**Comment by bradfitz** [comment]
That's also a netns issue, very similar to the one I fixed in the last day,
but for UDP where the address isn't known until after the netns dial.

**Comment by alexbrainman** [comment]
> That's also a netns issue, very similar to the one I fixed in the last day, but for UDP where the address isn't known until after the netns dial.

Wasted half of my Saturday (thank you very much).

https://github.com/tailscale/tailscale/pull/827

I still do not understand what the problem is. The error message I see is WSAEADDRNOTAVAIL.

https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2

> WSAEADDRNOTAVAIL10049 | Cannot assign requested address.The requested address is not valid in its context. This normally results from an attempt to bind to an address that is not valid for the local computer. This can also result from connect, sendto, WSAConnect, WSAJoinLeaf, or WSASendTo when the remote address or port is not valid for a remote computer (for example, address or port 0).
> -- | --
> 

And the error happens when we call WSASendTo. So, according to the error description, the problem should be remote address. But I can see remote address is set. It is local address that is set to 0.0.0.0.

Can you explain, @bradfitz ?

Alex

**Comment by alexbrainman** [comment]
The only remaining broken test is tailscale.com/portlist

```
--- FAIL: TestGetList (0.03s)
    portlist_test.go:20: addProcesses: netstat: exit status 1 ("")
--- FAIL: TestIgnoreLocallyBoundPorts (0.03s)
    portlist_test.go:41: addProcesses: netstat: exit status 1 ("")
FAIL
FAIL    tailscale.com/portlist  0.091s
```

The problem with the test is that it uses `netstat -nab` command, that can only run as Administrator. The test PASSes, if I run it from Administrator command window. What should I do? I don't see how these tests will run as Administrator ever. So the only thing that I can think of is to just skip the test.

I also don't understand how this code is useful, if it needs to be run by admin. I take it is running as a Windows service.

Alex

**Comment by bradfitz** [comment]
>  I don't see how these tests will run as Administrator ever. 

We could run our builder as Administrator. That might be useful considering how much of our code runs as a service.

> So the only thing that I can think of is to just skip the test.

In the meantime, why don't you pull the test is half? Test the parsing of `netstat -nab`'s output always (adding a big sample output string in the test file), but you can skip the execution of `netstat -nab` on Windows (or `t.Skip` after the exec fails, if on Windows).
