### ISSUE TITLE
tailscale ios app activates vpn automatically when opening app even though disabled

### ISSUE THREAD

**Issue by thescouser89** [tailscale/tailscale#539]
**Describe the bug**
I usually keep the VPN off (from the Settings app). However when opening the tailscale app, the VPN automatically shows as 'Connected' even though tailscale is disabled in the app.

This is really a minor bug though.

**To Reproduce**
1. Go to 'Settings' app, and disconnect from VPN. It should show as 'Not Connected'
2. Open Tailscale app. The 'status' is stopped
3. Go back to Settings app. The VPN shows as Connected.

**Expected behavior**
I'd expect the VPN to stay as 'Not Connected' when opening tailscale with status 'Stopped'. For example, the PIA app doesn't have the same behaviour as tailscale.

**Version information:**
 - Device: iphone 7
 - OS: iOS
 - OS version: 13.5.1
 - Tailscale version: 0.99.10069

**Additional context**
You guys rock!!! :)

**Comment by 0xtf** [comment]
Is there any update on this? I'm particularly concerned about possible battery usage. Even though it's probably minimal I currently need to make sure I go to settings to disable the VPN after I disable Tailscale.

**Comment by o42o** [comment]
I have installed an Apple Configuration Profile (https://apple.nextdns.io/) from NextDNS on my iOS device so I’m using my NextDNS account everywhere. But since I installed Tailscale, my device use the DNS server from the gateway or DHCP server because the VPN is connected even when I don’t use Tailscale.

More about profiles : https://developer.apple.com/business/documentation/Configuration-Profile-Reference.pdf

I don’t know the relationship between the profile and the VPN but if the VPN disconnect at the same time that I disconnect from Tailscale, the problem is resolved. 

Thank you for your amazing product by the way!

**Comment by Murgeye** [comment]
This issue is particularly annoying/serious since iOS seems to disable DNS over TLS/HTTPS profiles when a VPN is activated. While it is possible to work around this while Tailscale is actually activated (by pushing the DNS settings via Tailscale), I cannot use DNS over TLS/HTTPS while not connected anymore.

I think this might be the issue @o42o is experiencing as well. To reproduce:
1. Add a DNS over TLS profile to iOS, install, and activate it.
2. Check that DNS over TLS is actually used by iOS..
3. Install and connect to tailscale.
4. Disconnect from tailscale.
5. Go back to Settings app. The VPN shows as Connected.
6. Test if DNS over TLS is used (it is not).

Disabling in the settings app does not seem to work either, since it keeps activating.

**Comment by 0xtf** [comment]
Update? 🤷🏻‍♂️

**Comment by bradfitz** [comment]
Nope.

**Comment by nicokaiser** [comment]
Are there any news on this, especially when or if this will be resolved?

This is IMO a real blocker:

- When the VPN switch in the settings (not in the Tailscale app) is switched off, the VPN must be completely inactive (including DNS and routing). This is currently not the case: when switching off the VPN setting, it is being switched on again, as soon as the Tailscale app becomes active.

- On the other hand, when disabling Tailscale in the Tailscale app, some parts of the VPN is still active (as mentioned in previous comments, shows as connected, which seems to have an impact on battery life, and maybe also DNS).

=> Tailscale should be able to be completely switched on and off using the VPN switch in the Settings. And this switch should be completely in sync with the switch in the App.

This seems to concern at least the iOS and the macOS client.

**Comment by alie2n** [comment]
According to my battery view in the settings app, the tailscale app used about 7% battery life in the last 10 days. Viewing only yesterday it was 23% which is quite unacceptable.
Any news on this would be awesome.

**Comment by renna999** [comment]
Is there any update on this? I’m also facing battery drain issues and the before mentioned setup quirks. Thank you!

**Comment by ibash** [comment]
This is a frustrating bug. The only fix I've found is to force quit the tail scale app, and then go to the VPN settings to manually disconnect tailscale, when tailscale is not in use. 

I can understand the desire to make the connection quick by preemptively establishing the vpn, but at the very least make it an option to disable that behavior.

**Comment by chr-lei** [comment]
> This issue is particularly annoying/serious since iOS seems to disable DNS over TLS/HTTPS profiles when a VPN is activated. While it is possible to work around this while Tailscale is actually activated (by pushing the DNS settings via Tailscale), I cannot use DNS over TLS/HTTPS while not connected anymore.
> 
> I think this might be the issue @o42o is experiencing as well. To reproduce:
> 
> 1. Add a DNS over TLS profile to iOS, install, and activate it.
> 2. Check that DNS over TLS is actually used by iOS..
> 3. Install and connect to tailscale.
> 4. Disconnect from tailscale.
> 5. Go back to Settings app. The VPN shows as Connected.
> 6. Test if DNS over TLS is used (it is not).
> 
> Disabling in the settings app does not seem to work either, since it keeps activating.

I’m experiencing this same issue. iOS will favor any DNS settings configured in a VPN, and even if no custom DNS settings are pushed, it will bypass the DoH/DoT settings if a VPN is active. I didn’t notice the incomplete disconnect issue until tonight when I realized I was seeing ads on my phone. Checked the app and it was not connected, but the Settings app showed still connected. I was leaking DNS queries all day today since deactivating Tailscale on the phone this morning.  I don’t even know what the toggle in the app does at this point. I’m more than willing to provide logs or test if a fix is available.

**Comment by mrreview** [comment]
Any news on this? If I enable VPN from iOS settings, VPN is not really enabled until I open Tailscale app and enable it there... this behavior wasn't happening with WireGuard app, I always enabled/disabled the VPN from iOS settings without the need to do anything on the app. Thank you

**Comment by ravens** [comment]
Still observing this battery issue when I disable the app switch but forget to disable the VPN one. Could we get a configuration knob in the settings part of the app so that the slider in the VPN OS switch follow the behaviour of the Tailscale switch (Active/Stopped) in the app ?

**Comment by 0xtf** [comment]
> Still observing this battery issue when I disable the app switch but forget to disable the VPN one. Could we get a configuration knob in the settings part of the app so that the slider in the VPN OS switch follow the behaviour of the Tailscale switch (Active/Stopped) in the app ?

At this point, all you’ll get is your comment marked as duplicate. 

Yes Tailscale, if a bug is affecting users for 3+ years and there’s no reply you’ll get “duplicate” comments.

**Comment by ravens** [comment]
@0xtf I am fine with that - but I am also making a suggestion to change the behaviour of the slider.

**Comment by onestix** [comment]
Surprised to see this issue's been open for so long. Hoping for a solution here.

**Comment by tmchow** [comment]
Echoing what everyone else says:

1. I'm able to repro this
2. It's bad for battery life
3. Unexpected

**Comment by Gymnae** [comment]
+1 - even with the latest beta. Also, no on-demand

**Comment by emax810** [comment]
new beta (1.45.35 ) : same issue !!!

**Comment by Gymnae** [comment]
@nickoneill , I think the label „L2 Few“ is not fitting, since all iOS users are affected

**Comment by Gymnae** [comment]
Same issue with Testflight version 1.45.56

**Comment by apix0n** [comment]
Same issue with TestFlight version 1.46.0

**Comment by apix0n** [comment]
Seems fixed in TestFlight version 1.47.37 !

**Comment by Biepa** [comment]
The Tailscale VPN is still activating as soon as I open the app. But "disconnecting" in the app actually stops the VPN and reflecting that in the iOS settings.

**Comment by agottardo** [comment]
> Could we get a configuration knob in the settings part of the app so that the slider in the VPN OS switch follow the behaviour of the Tailscale switch (Active/Stopped) in the app ?

Good news for all of you folks here: I have just fixed this in the [latest TestFlight version](https://testflight.apple.com/join/tLcYLZJV) (1.47.37), and I encourage you to try it out. The fix will also make its way into our App Store release soon. Now, when you tap disconnect in the app, or disconnect Tailscale via a Shortcuts action, the VPN process will be terminated entirely, reflecting this in the Settings app. This should help improve battery life.

This might seem like a small change, but behind the scenes it required significant changes in the architecture of the app. If you are running our TestFlight, I would really appreciate if you could report any bugs you see. Thanks! 🙏🏻 

Also, many of you here are asking for On-Demand VPN. I'm happy to report we are actively working on it! Expect news soon 🙂

**Comment by o42o** [comment]
Wow good work! The bug is fixed on TestFlight. Thank you!

**Comment by pindab0ter** [comment]
Thank you for putting in the effort. It is much appreciated!

**Comment by mrreview** [comment]
Thank you for the effort. I'm testing the latest TestFlight (iOS 16.6). But I'm still having issues. If I turn on the VPN from Settings, then it won't enable until I open or switch to the Tailscale App. Maybe is this the expected behavior? I appreciate all the effort you're putting in this.

**Comment by agottardo** [comment]
> Thank you for the effort. I'm testing the latest TestFlight (iOS 16.6). But I'm still having issues. If I turn on the VPN from Settings, then it won't enable until I open or switch to the Tailscale App. Maybe is this the expected behavior? I appreciate all the effort you're putting in this.

Thanks, I am aware of the issue. A fix is on the way, likely landing in the next TestFlight update. For now, ensure you start Tailscale from the app or via Shortcuts.

**Comment by mrreview** [comment]
> > Thank you for the effort. I'm testing the latest TestFlight (iOS 16.6). But I'm still having issues. If I turn on the VPN from Settings, then it won't enable until I open or switch to the Tailscale App. Maybe is this the expected behavior? I appreciate all the effort you're putting in this.
> 
> Thanks, I am aware of the issue. A fix is on the way, likely landing in the next TestFlight update. For now, ensure you start Tailscale from the app or via Shortcuts.

Nice! Working good in both, Shortcuts and App.
