### ISSUE TITLE
XDG_RUNTIME_DIR not set when running a command through Tailscale ssh

### ISSUE THREAD

**Issue by groves** [tailscale/tailscale#5715]
### What is the issue?

When I run a command using Tailscale's ssh, `XDG_RUNTIME_DIR` isn't set. When I run a command over ssh directly to the same server, it is. `XDG_RUNTIME_DIR` is set by both Tailscale ssh and direct ssh if I login.

I found this using [Kitty's ssh wrapper](https://sw.kovidgoyal.net/kitty/kittens/ssh/). When I switched to using Tailscale ssh with it, I could no longer use `ssh-agent` with a "Could not open a connection to your authentication agent" error. After some digging, it looked like my `SSH_AUTH_SOCK` wasn't set due to `XDG_RUNTIME_DIR` being unset. Kitty's ssh wrapper runs some commands to set up its shell integration before execing your login shell, so it's going through the "run command" ssh path instead of the "login" ssh path.

I'm guessing `XDG_RUNTIME_DIR` isn't set because [incubator_linux.go calls CreateSession directly](https://github.com/tailscale/tailscale/blob/a7a0baf6b9952d6528bf75c5c8618f9f49548ef2/ssh/tailssh/incubator_linux.go#L127). The [docs for CreateSession](https://www.freedesktop.org/software/systemd/man/org.freedesktop.login1.html) say to never invoke it directly and instead use pam_systemd. [pam_systemd](https://www.freedesktop.org/software/systemd/man/pam_systemd.html) says it's responsible for setting `XDG_RUNTIME_DIR`. It looks like calling [pam_sm_open_session](https://github.com/systemd/systemd/blob/4d0d34b4e7054f7bef105ed1ec27f976778c5c4e/src/login/pam_systemd.c#L732) would both call CreateSession and set `XDG_RUNTIME_DIR`. I imagine calling `pam_sm_open_session` is easier said than done, but that's at least where my investigation got to.

I'd further guess it works when I'm logging in as that calls the `login` command and that probably calls something pam related deep in it.

### Steps to reproduce

`altex` is the Tailscale name of a machine of mine, `192.168.1.147` is its non-Tailscale IP, and `kabyle` is the machine I'm logging in from. This is a shell session showing `XDG_RUNTIME_DIR` not being set when running a command through Tailscale ssh and it being set otherwise.

```
groves@kabyle ~> ssh altex env | grep XDG_RUN
groves@kabyle ~ [0|1]> ssh 192.168.1.147 env | grep XDG_RUN
XDG_RUNTIME_DIR=/run/user/1000
groves@kabyle ~> ssh altex
groves@altex ~> env | grep XDG_RUN
XDG_RUNTIME_DIR=/run/user/1000
groves@altex ~> 
groves@kabyle ~> ssh 192.168.1.147
groves@altex ~> env | grep XDG_RUN
XDG_RUNTIME_DIR=/run/user/1000

### Are there any recent changes that introduced the issue?

_No response_

### OS

Linux

### OS version

NixOS 22.05 using an unstable from September 20th

### Tailscale version

1.30.2

### Bug report

BUG-ea00c1a944b65fc8251d64f889bc3cf3878321eca2272ec07d786793627cf6b3-20220921210433Z-efc466713139bc9f

**Comment by DentonGentry** [comment]
XDG_RUNTIME_DIR  was also mentioned in https://github.com/tailscale/tailscale/issues/4940

Fixed by https://github.com/NixOS/nixpkgs/pull/180364

**Comment by TheOnlyMrCat** [comment]
I'm still experiencing this issue: `ssh 100.65.124.36` correctly sets `XDG_RUNTIME_DIR`, but `kitten ssh 100.65.124.36` does not. This happens when ssh'ing into my NixOS server and my Ubuntu server.

NixOS server: Tailscale 1.56.1 on Linux 6.1.21, NixOS 24.05.20240106.46ae021
Ubuntu server: Tailscale 1.56.1 on Linux 5.15.0-91-generic, Ubuntu 22.04.3 LTS
Local machine: OpenSSH_9.6p1, kitty 0.31.0 on Linux 6.6.8, NixOS 24.05.20240106.46ae021
