### ISSUE TITLE
100% Reproducible 100% CPU hug on macos while connected to an exit node

### ISSUE THREAD

**Issue by alimoeeny** [tailscale/tailscale#5804]
### What is the issue?

IPNExtension hugs the CPU and prevents network operations if you switch to wifi hotspot while connected to an exit node. 

### Steps to reproduce

1. connected to some wifi 
2. connect to an exit node
3. walk away from the wifi so that the wifi is not in range anymore 
4. [not sure if this is essential] macos also goes into sleep (because it take a while to walk away)
5. connect to a mobile hotspot (I only tried with iOS on iPhone 10 and iPhone 13)
6. IPNExtension starts using 100% CPU and although the mac UI shows you'r connected to the network, most (all?) network operations just don't work or are stuck
7. to solve it you need to disconnected from the exit node 
8. you can connect back to exit node if you want and all works well. 

### Are there any recent changes that introduced the issue?

NO, this has been a problem since I started using tailscale many many months (more than a year) ago. 

### OS

macOS

### Tailscale version

12.x and 13.x

### Bug report

BUG-cc5167d0806daf2f4cbdf738e58c1b7a622959e79e7237d8421c8748b4367b05-20221001115728Z-de7e4f28d76bf45b

**Comment by alimoeeny** [comment]
Of course I'd be happy to help debug this in anyway I can, including running dev version of the app, or running things under debugger or sending over logs etc.

**Comment by DentonGentry** [comment]
This may have been fixed by [#5940](https://github.com/tailscale/tailscale/pull/5940), which went into Tailscale release 1.32.2 for macOS.

**Comment by alimoeeny** [comment]
thank you @DentonGentry  , unfortunately in 1.32.2 this issue is still not fixed.

**Comment by simonfalke-01** [comment]
https://forum.tailscale.com/t/ipnextension-uses-400-cpu-when-connected/1340
Similar issue, IPNExtension uses 400% CPU after waking from sleep connected to an Exit Node. Tailscale version 1.34.1, macOS Ventura.

**Comment by mihaip** [comment]
This may be similar to #5156 (another routing loop). There is a tentative fix for that in the unstable build (https://github.com/tailscale/tailscale/issues/5156#issuecomment-1344542656), if anyone that is experiencing this would like to try it ahead of the 1.36 stable release.

**Comment by DentonGentry** [comment]
At this point I think this is the same issue as https://github.com/tailscale/tailscale/issues/5156, marking as a duplicate.
