### ISSUE TITLE
Browser SSH console renders too many underlines

### ISSUE THREAD

**Issue by octylFractal** [tailscale/tailscale#6090]
### What is the issue?

The SSH console renders a bunch of underlines where there aren't any in a more standard vterm like Konsole:
![Tailscale SSH Console](https://url.octyl.net/wek0rlccqap42bj6zwsj)
![Konsole](https://url.octyl.net/x7nw8n4338pbcs4p4ino)

### Steps to reproduce

1. SSH into a machine
2. Run `ponysay` to get the help output.

### OS

Linux, Other

### OS version

Linux 6.0.2-zen1-1-zen

### Tailscale version

1.32.1 (Target machine) / 1.33.0-dev20221025 (console)

### Bug report

BUG-37c635370a18c62c5fc64d92cf69e4c3f5450f8abd38dc56437874bbb5e90188-20221027173137Z-d69cabc2357613b3

**Comment by bradfitz** [comment]
cc @mihaip 

Also we probably need a new GitHub label. `ssh` might be a bit overloaded.

**Comment by mihaip** [comment]
This appears to be an issue in the underlying terminal emulation package that we use (xterm.js). I believe https://github.com/xtermjs/xterm.js/pull/4216 will fix, will verify once that is merged.

**Comment by DentonGentry** [comment]
Believed fixed by https://github.com/tailscale/tailscale/pull/7079

**Comment by mihaip** [comment]
Not fixed, the commit message says "Unfortunately it's not enough to fix the issue with `ponysay`, but it does not hurt to be up to date."
