### ISSUE TITLE
Harmless PCP map errors in router logs (seemingly) caused by tailscaled on raspberry pi

### ISSUE THREAD

**Issue by andybons** [tailscale/tailscale#810]
**Describe the bug**
I’m running tailscale on my raspberry pi, and my router is showing the following (benign) errors repeatedly (192.168.50.244 is the pi):

<details>
<summary>Router logs</summary>

```
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: PCP MAP: failed to add mapping UDP 0->192.168.50.244:0 'PCP MAP 7ed3eaa1041b0ec7b8b44166'
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: Failed to remove PCP mapping internal port 0, protocol UDP
Oct  6 22:17:03 miniupnpd[4133]: PCP: External IP in request didn't match interface IP 
Oct  6 22:17:03 miniupnpd[4133]: PCP MAP: failed to add mapping UDP 0->192.168.50.244:0 'PCP MAP 864f0d611e688e35bc49a0e8'
```
</details>

When I stop `tailscaled.service` the errors stop, and when I start it up again they resume, so I’m assuming with very little data that it is the cause. Below are the `version` and `netcheck` outputs:

```
$ tailscale netcheck

Report:
	* UDP: true
	* IPv4: yes, <redacted>
	* IPv6: yes, <redacted>
	* MappingVariesByDestIP: false
	* HairPinning: false
	* PortMapping: UPnP, NAT-PMP, PCP
	* Nearest DERP: 1 (nyc)
	* DERP latency:
		- 1, nyc = 26.3ms
		- 2, sfo = 93.5ms
		- 3, sin = 267.6ms
		- 4, fra = 109.6ms
		- 5, syd = 233.5ms
$ tailscale version
1.0.5-g31b5dec0a
```

**To Reproduce**
1. Running the `tailscaled.service`
2. See errors in router logs

**Expected behavior**
No errors in router logs

**Version information:**
 - Device: ASUS RT-AX88U
 - OS: Standard router firmware
 - OS version: 3.0.0.4.384_9566-g7411682
 - Tailscale version: 1.0.5-g31b5dec0a

**Additional context**

Notes from @bradfitz from email exchange with info@

> PMP and UPnP we can query without side effects. PCP requires an action to learn whether it exists. But it should be a harmless no-op action that succeeds, then we should un-do it, and we shouldn't be doing it super often.

I’ve tried sshing into the router to get the miniupnpd version but that’s proving to be difficult as the command seems to be at a version that [doesn’t provide a way to get the version from the binary](https://github.com/miniupnp/miniupnp/issues/370) and I can’t seem to find the version number in syslog. Any other ways to get that info?

Love the product! Keep up the good work!

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2c0sx)

**Comment by bradfitz** [comment]
Various thoughts, @danderson:

* despite all those errors, it does detect PCP.

* we probably only need to do PCP detection at most once per LinkChange.

* "External IP in request didn't match interface IP" makes it sound like the router is expecting an external IP. In https://tools.ietf.org/html/rfc6887#section-11.1 we're populating the "Suggested External IP address" as `v4unspec.As16()`:

```go
func pcpPacket(myIP netaddr.IP, mapToLocalPort int, delete bool) []byte {
        const udpProtoNumber = 17
        lifetimeSeconds := uint32(1)
        if delete {
                lifetimeSeconds = 0
        }
        const opMap = 1
        pkt := make([]byte, (32+32+128)/8+(96+8+24+16+16+128)/8)
        pkt[0] = 2 // version                                                                                                                                                   
        pkt[1] = opMap
        binary.BigEndian.PutUint32(pkt[4:8], lifetimeSeconds)
        myIP16 := myIP.As16()
        copy(pkt[8:], myIP16[:])
        rand.Read(pkt[24 : 24+12])
        pkt[36] = udpProtoNumber
        binary.BigEndian.PutUint16(pkt[40:], uint16(mapToLocalPort))
        v4unspec16 := v4unspec.As16()
        copy(pkt[40:], v4unspec16[:])
        return pkt
```

The spec says:

>    Suggested External IP Address:  Suggested external IPv4 or IPv6
>      address.  This is useful for refreshing a mapping, especially
>    after the PCP server loses state.  If the PCP client does not know
>    the external address, or does not have a preference, it MUST use
>    the address-family-specific all-zeros address (see Section 5).

But section 5 says to do what we're doing:

https://tools.ietf.org/html/rfc6887#section-5

So, I guess it's fine and we can just reduce the frequency of the PCP map requests?

**Comment by joeshaw** [comment]
I also see this on my Ubiquiti EdgeRouter, as well as frequent `PCP: Invalid PCP v2 MAP message.` log lines.

**Comment by kangaroo** [comment]
I'm also seeing this on my Ubiquiti router, but of more concern it seems to be consuming 100% of a core sending this traffic constantly.  I also see very high cpu use on one of my tailscale nodes.

**Comment by deasmi** [comment]
I am also seeing this using Opnsense as a router/firewall. 

As I have a few tailscale devices on net this is filling up circular logs very quickly and preventing any actual logs being visible. 

Version installed

miniupnpd-2.1.20190210,1 

`
Nov 24 08:10:25 redact miniupnpd[76945]: Failed to remove PCP mapping internal port 0, protocol UDP
Nov 24 08:10:25 redact miniupnpd[76945]: PCP: External IP in request didn't match interface IP
`

**Comment by zachberger** [comment]
I see this too on my Ubiquiti Dream Machine Pro too, here is the breakdown of the logs I've received over the last 5 minutes indicating this is happening about 50 times per second:

<img width="610" alt="Screen Shot 2020-12-06 at 10 49 37 AM" src="https://user-images.githubusercontent.com/1634878/101289387-f3dc3980-37b0-11eb-833d-7599ac694a3f.png">

**Comment by bradfitz** [comment]
I just pushed a fix (https://github.com/tailscale/tailscale/commit/05e5233e07857dea256c3d1b0088b368cf9f5243) for the flood of requests and cherry-picked it to the 1.2 stable branch. It'll be in 1.2.10. I'll also cut an unstable build tomorrow. (which will be numbered something greater than 1.3.87)

I'll keep this open until I've verified it's good for everybody.

**Comment by bradfitz** [comment]
1.3.95 is out with the fix at https://pkgs.tailscale.com/unstable/

Let me know how it acts?

(1.2.10 will come later this week probably)

**Comment by zachberger** [comment]
I'm still seeing a ton of log entries

<img width="1170" alt="Screen Shot 2020-12-07 at 3 23 03 PM" src="https://user-images.githubusercontent.com/1634878/101417210-2fa1fc80-38a0-11eb-9ded-697b79eb3416.png">

```
ubuntu@192.168.86.10:~$ tailscale version
1.3.95
  tailscale commit: 442d1873ec7b8ca211e18041c1be7edb48e70d48
  other commit: 5a5f1aac781f0f8a03b57dc90a15de5b3ac68bf3
  go version: go1.15.5-ts3bd8919
```


```
ubuntu@192.168.86.11:~$ tailscale version
1.3.95
  tailscale commit: 442d1873ec7b8ca211e18041c1be7edb48e70d48
  other commit: 5a5f1aac781f0f8a03b57dc90a15de5b3ac68bf3
  go version: go1.15.5-ts3bd8919
```

**Comment by bradfitz** [comment]
@zachberger, that's about what I expected. I only fixed the flood of requests, not the content of the requests. I haven't yet investigated why miniupnpd is unhappy, but I was earlier able to repro that.

**Comment by zachberger** [comment]
After some further investigation, it seems to be orders of magnitude better, going from ~2000 per minute to about 20

<img width="1440" alt="Screen Shot 2020-12-07 at 3 26 57 PM" src="https://user-images.githubusercontent.com/1634878/101417522-b1922580-38a0-11eb-9b34-0894d3de25dd.png">

**Comment by bradfitz** [comment]
Great. Good to see that confirmed, thanks!

I'll work on making miniupnpd happy next.

**Comment by bradfitz** [comment]
The relevant code in `miniupnpd/pcpserver.c` is:

```c
        if (pcp_msg_info->ext_ip == NULL ||
            IN6_IS_ADDR_UNSPECIFIED(pcp_msg_info->ext_ip) ||
            (IN6_IS_ADDR_V4MAPPED(pcp_msg_info->ext_ip)
              && ((uint32_t *)pcp_msg_info->ext_ip->s6_addr)[3] == INADDR_ANY)) {
                /* no suggested external address : use real external address */
                pcp_msg_info->ext_ip = &external_addr;
                return 0;
        }

        if (!IN6_ARE_ADDR_EQUAL(pcp_msg_info->ext_ip, &external_addr)) {
                syslog(LOG_ERR,
                       "PCP: External IP in request didn't match interface IP \n");
#ifdef DEBUG
                {
                        char s[INET6_ADDRSTRLEN];
                        syslog(LOG_DEBUG, "Interface IP %s \n",
                               inet_ntop(AF_INET6, &external_addr.s6_addr, s, sizeof(s)));
                        syslog(LOG_DEBUG, "IP in the PCP request %s \n",
                               inet_ntop(AF_INET6, pcp_msg_info->ext_ip, s, sizeof(s)));
                }
#endif
```

It's trying to compare our v6-mapped IPv4 address in the PCP packet with the IPv6 address of the interface?

Building miniupnpd with DEBUG now to verify.

**Comment by bradfitz** [comment]
```
miniupnpd[424260]: PCP request received from 10.0.0.52:45570 60bytes
miniupnpd[424260]: PCP: External IP in request didn't match interface IP 
miniupnpd[424260]: Interface IP ::ffff:209.180.207.183 
miniupnpd[424260]: IP in the PCP request 0:0:0:ffff:: 
miniupnpd[424260]: chain MINIUPNPD not found
miniupnpd[424260]: Failed to remove PCP mapping internal port 0, protocol UDP
```

**Comment by bradfitz** [comment]
Ah! I was writing the v6-mapped v4-unspecified address 4 bytes too early in the PCP packet.

**Comment by bradfitz** [comment]
Fixed. I also opened https://github.com/tailscale/tailscale/issues/1001 to do this even less, though.

**Comment by bradfitz** [comment]
1.2.10 for Linux is released with the fix for this. Other platforms coming soon-ish.
